import {installHUD} from './ui/hud.js';
import {installLivingUI} from './ui/living.js';
import {installCity} from './ui/city.js';import {installArena} from './ui/arena.js';import {openPhotoAvatar} from './ui/photo-avatar.js';import {installHudLayout} from './ui/hud-layout.js';import {installDriveHud,wobbleInput} from './ui/drive-hud.js';import {installJobs} from './ui/jobs.js';
import {resetPaths,PointerMove,setExtraBlock,resetPaths as resetPaths3d} from './player/pointer.js';import {LOOKS} from '/shared/looks.js';
import {Renderer} from './world/renderer.js';import {Controls} from './player/controls.js';import {api,setToken,token,Connection,server,setServer,nativeApp} from './networking/api.js';import {Voice} from './audio/voice.js';import {Calls} from './audio/calls.js';import {applyMapEdits,MAPS,doors,distance,step} from '/shared/world.js';
const $=id=>document.getElementById(id),renderer=new Renderer($('world')),net=new Connection();let user=null,me=null,largeMap=null,players=[],display=new Map(),toastTimer,frames=0,lastFps=performance.now();
function notify(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500);}
const voice=new Voice(net,notify),calls=new Calls(net,notify),controls=new Controls($('joystick'),$('run'),()=>$('interact').onclick());
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn){const b=el('button',text);b.onclick=()=>Promise.resolve().then(fn).catch(e=>notify(e.message));return b;}
function modal(title){$('modal').classList.remove('atm-full');controls.reset();controls.enabled=false;$('modal-title').textContent=title;$('modal-body').replaceChildren();if(!$('modal').open)$('modal').showModal();return $('modal-body');}
function closeModal(){largeMap=null;$('modal').close();controls.reset();controls.enabled=!!me;}
$('modal-close').onclick=closeModal;$('modal').addEventListener('close',()=>{controls.reset();controls.enabled=!!me;});
async function enter(data,create=false){user=data.user;setToken(data.token);await net.connect();$('auth').hidden=true;$('hud').hidden=false;$('my-name').textContent=user.username;controls.enabled=true;try{await livingUI.load();}catch(e){notify('Il mondo è connesso; caricamento preferenze non riuscito: '+e.message);}if(create){profile();notify('BENVENUTO IN HUMANA · Muoviti, esplora, incontra persone, parla, entra nei locali.');}else notify('Benvenuto sul Lungomare. WASD o joystick per muoverti.');setTimeout(()=>city.confirmCheckout(),1500);}
let authenticating=false;
// App sul telefono: chiede al lanciatore sul PC (porta 3078) di accendere il gioco e aspetta che risponda.
async function wakeServer(address){if(!nativeApp)return;const base=(address||server||'').replace(/\/+$/,'');if(!/^https?:\/\//.test(base))return;const host=base.replace(/:\d+$/,'');const ping=()=>fetch(base+'/api/auth/options',{signal:AbortSignal.timeout(2500)}).then(r=>r.ok).catch(()=>false);
 if(await ping())return;$('auth-error').textContent='⏳ Avvio del server sul PC…';try{await fetch(host+':3078/avvia',{signal:AbortSignal.timeout(15000)});}catch{}for(let i=0;i<20;i++){if(await ping()){$('auth-error').textContent='';return;}await new Promise(r=>setTimeout(r,700));}
 $('auth-error').textContent='Il PC non risponde: controlla che sia acceso, sulla stessa rete Wi-Fi e con il lanciatore attivo.';}
async function authenticate(register){if(authenticating)return;authenticating=true;$('auth-error').textContent='';const form=new FormData($('auth-form'));try{if(nativeApp){const address=$('server').value.trim();if(!/^https?:\/\/[^\s/?#]+$/.test(address.replace(/\/+$/,'')))throw new Error('Indirizzo server non valido. Esempio: http://192.168.1.10:3000');setServer(address);renderer.assetBase=address.replace(/\/+$/,'');renderer.art=null;renderer.artLoading=false;await wakeServer(address);}const data=await api('/auth/'+(register?'register':'login'),'POST',Object.fromEntries(form));await enter(data,register);}catch(e){$('auth-error').textContent=e.message;}finally{authenticating=false;}}
if(nativeApp){$('server-field').hidden=false;$('server').value=server||'http://192.168.1.36:3077';$('server').required=true;}
// HUMANA life 3D: scelta del personaggio pronto (ritratti in assets/personaggi) e ingresso da ospite senza account.
function pickLook(title,done){const box=modal(title),grid=el('div');grid.style.cssText='display:grid;grid-template-columns:repeat(4,1fr);gap:10px';const err=el('p');err.setAttribute('role','alert');
 LOOKS.forEach((L,i)=>{const b=el('button');b.type='button';b.style.cssText='padding:6px 4px 8px;display:flex;flex-direction:column;align-items:center;gap:4px;color:#fff;background:#0f2233;border:2px solid '+(user?.avatar?.look===i?'#f5b81c':'#24465e')+';border-radius:14px;cursor:pointer';
  const im=new Image();im.src=(renderer.assetBase||'')+'/assets/personaggi/'+(i+1)+'.webp';im.alt=L.name;im.style.cssText='height:150px;max-width:100%;object-fit:contain';b.append(im,el('strong',L.name));
  b.onclick=()=>{err.textContent='';Promise.resolve().then(()=>done(i)).catch(e=>{err.textContent=e.message;});};grid.append(b);});
 box.append(grid,err);
 if(window.HUMANA_3D){const pb=button('📷 Crea il tuo avatar da una foto',()=>openPhotoAvatar({modal,el,button,notify,closeModal,base:renderer.assetBase||'',onPick:(look,photo)=>{Promise.resolve().then(()=>done(look,photo)).catch(e=>notify(e.message));}}));pb.style.marginTop='10px';box.append(pb);}}

// HUMANA life 3D online: la pagina si apre subito dalla memoria del telefono, ma il server gratuito dorme dopo 15 minuti senza visite e ci mette fino a un minuto a svegliarsi.
// Appena la pagina si apre lo si sveglia e si scrive chiaramente cosa succede, invece di restare muti.
let serverReady=!window.HUMANA_3D||/^(localhost|127.0.0.1|192.168.)/.test(location.hostname);
if(!serverReady){const note=$('auth-error'),t0=Date.now();const msg=()=>{if(serverReady||!note||authenticating)return;note.textContent='⏳ Sto svegliando il gioco… la prima volta può servire un minuto ('+Math.round((Date.now()-t0)/1000)+' s)';};setTimeout(msg,1200);const tick=setInterval(msg,1000);(async()=>{for(let i=0;i<4&&!serverReady;i++){try{const r=await fetch('/api/config',{cache:'no-store',signal:AbortSignal.timeout(75000)});if(r.ok)serverReady=true;}catch{}}clearInterval(tick);if(note&&note.textContent.startsWith('⏳'))note.textContent=serverReady?'✅ Gioco pronto: tocca GIOCA SUBITO':'Il gioco non risponde. Controlla la connessione e riprova.';})();}
if($('guest'))$('guest').onclick=async()=>{if(authenticating)return;if(token){try{const u=await api('/me');await enter({user:u,token});return;}catch{}}pickLook('Scegli il tuo personaggio',async (i,photo)=>{if(authenticating)return;authenticating=true;try{if(!serverReady)notify('⏳ Sto avviando il gioco, attendi…');const data=await api('/auth/guest','POST',{look:i,photo});serverReady=true;closeModal();notify('⏳ Carico il mondo… la prima volta può servire un minuto');await enter(data);notify('Benvenuto, '+data.user.username+'! Muoviti con WASD o col joystick.');}finally{authenticating=false;}});};
$('auth-form').onsubmit=e=>{e.preventDefault();authenticate(false);};$('register').onclick=()=>{if($('auth-form').reportValidity())authenticate(true);};
// Autoradio: suona il video scelto da chi guida (per il guidatore e i suoi passeggeri).
let radioId=null,jukeNow=null;const radio=()=>{let src=me&&(me.vehicle?me:me.seat==='car'?players.find(q=>q.id===me.passenger):null),id=src?.vehicle&&src.music?src.music+'@'+src.musicAt:null;if(!id&&jukeNow&&me){src={music:jukeNow.id,musicAt:jukeNow.at,musicTitle:jukeNow.title,juke:true};id='jb:'+jukeNow.id+'@'+jukeNow.at;}if(id===radioId)return;radioId=id;document.getElementById('car-radio')?.remove();if(!id)return;const f=document.createElement('iframe');f.id='car-radio';f.allow='autoplay; encrypted-media';f.referrerPolicy='strict-origin-when-cross-origin';f.style.cssText='position:fixed;left:-400px;bottom:0;width:320px;height:180px;border:0;opacity:0;pointer-events:none';f.src='https://www.youtube-nocookie.com/embed/'+src.music+'?autoplay=1&playsinline=1&start='+Math.max(0,Math.floor((Date.now()-src.musicAt)/1000));document.body.append(f);if(src.juke)notify('🎵 Jukebox: '+(src.musicTitle||'musica'));else if(src===me||src.musicTitle)notify('📻 In auto: '+(src.musicTitle||'musica'));};
window.humanaCar=()=>!!me?.vehicle;addEventListener('humana-arrived',e=>notify('📍 Sei arrivato'+(e.detail?.name?': '+e.detail.name:'')));addEventListener('humana-travel',e=>net.send({type:'travel',to:e.detail}));addEventListener('humana-car-music',e=>net.send({type:'carMusic',...e.detail}));
net.addEventListener('state',e=>{const state=e.detail;jukeNow=state.jukebox||null;window.humanaJuke=jukeNow;if(!window.HUMANA_3D&&me?.room==='mergellina'&&!state.__back){state.__back=1;net.send({type:'travel',to:'lungomare'});}queueMicrotask(radio);if(state.online!==undefined){const o=$('online-count');if(o)o.textContent='🟢 Online: '+state.online;}renderer.worldTime=state.now;if(state.roomDefinition)MAPS[state.roomDefinition.id]=state.roomDefinition;players=state.players;const own=players.find(p=>p.id===net.id);if(!own)return;
 // Zona che questa edizione non conosce (es. si era a Mergellina nel 3D e si apre il 2D): si torna sul Lungomare e si aspetta, senza errori.
 if(!MAPS[own.room]){if(!window.HUMANA_3D&&Date.now()-(net.backAt||0)>1500){net.backAt=Date.now();net.send({type:'travel',to:'lungomare'});}return;}
 const changed=me&&me.room!==own.room;if(changed){display.clear();controls.reset();notify(MAPS[own.room]?.name||'Mergellina');}
 const ids=new Set(players.map(p=>p.id));for(const id of display.keys())if(!ids.has(id))display.delete(id);
 for(const p of players){let d=display.get(p.id);if(!d||d.room!==p.room){d={...p,targetX:p.x,targetY:p.y};display.set(p.id,d);}else{const x=d.x,y=d.y;Object.assign(d,p,{targetX:p.x,targetY:p.y});d.x=p.seat?p.x:x;d.y=p.seat?p.y:y;}}
 me=display.get(net.id);$('auth').hidden=true;$('hud').hidden=false;miniMap($('minimap'),players,me);if(recovering){recovering=false;controls.enabled=!$('modal').open;notify('Connessione ripristinata');}voice.state(players,own);$('area').textContent=MAPS[own.room]?.name||'Mergellina';$('online').textContent=state.online+' online';$('connection').textContent='● Connesso · '+players.length+' in zona'+(net.latency===null||net.latency===undefined?'':' · '+net.latency+' ms');
});
net.addEventListener('chat',e=>{if(window.HUMANA_3D&&e.detail.id!==net.id&&!document.body.classList.contains('chat-open')){const tg=$('chat-toggle');if(tg)tg.dataset.n=String(Math.min(99,(Number(tg.dataset.n)||0)+1));}renderer.bubbles??=new Map();renderer.bubbles.set(e.detail.id,{text:e.detail.text.slice(0,70),until:performance.now()+5500});const line=el('div');line.append(el('b',e.detail.username),document.createTextNode(e.detail.text));$('messages').append(line);while($('messages').childElementCount>40)$('messages').firstChild.remove();$('messages').scrollTop=$('messages').scrollHeight;});
net.addEventListener('error',e=>notify(e.detail.message));net.addEventListener('disconnected',e=>{voice.stop();calls.cleanup();controls.reset();controls.enabled=false;me=null;players=[];display.clear();$('hud').hidden=true;$('auth').hidden=false;$('auth-error').textContent=e.detail;closeModal();});
let lastChatSent=0;
$('chat-form').onsubmit=e=>{e.preventDefault();if(Date.now()-lastChatSent<650){notify('Attendi un istante prima di inviare un altro messaggio.');return;}lastChatSent=Date.now();const text=$('chat-input').value.trim();if(text)net.send({type:'chat',text});$('chat-input').value='';$('chat-input').blur();};$('chat-toggle').onclick=()=>{$('chat').hidden=!$('chat').hidden;if(!$('chat').hidden)$('chat-input').focus();};
$('interact').onclick=()=>{if(!me)return;if(!doors(me.room).some(d=>distance(d,me)<1.65)&&city.interact(me))return;const usable=doors(me.room).some(d=>distance(d,me)<1.65)||MAPS[me.room].props.some(p=>p.kind==='seat'&&distance(p,me)<1.35)||me.seat||(!me.vehicle&&players.some(q=>q.id!==me.id&&q.vehicle&&distance(q,me)<2.6));if(usable)net.send({type:'interact'});else{const near=players.find(p=>p.id!==me.id&&distance(p,me)<2);if(near)showPerson(near);else notify('Avvicinati a una porta, una sedia o una persona.');}};$('emote').onclick=()=>{const box=modal('Come ti senti?');for(const value of ['👋','❤️','🎉','💃','😂','👏']){const row=el('div',undefined,'row');row.append(button(value+' Gesto',()=>{net.send({type:'emote',value});closeModal();}),button(value+' Nella chat',()=>{$('chat-input').value=($('chat-input').value+value).slice(0,300);$('chat').hidden=false;closeModal();$('chat-input').focus();}));box.append(row);}};
async function toggleVoice(){try{if(voice.enabled){voice.setMuted(!voice.muted);$('voice').classList.toggle('active',!voice.muted);$('voice').classList.toggle('muted',voice.muted);notify(voice.muted?'🔇 Microfono spento · continui a sentire gli altri':'🎙️ Microfono acceso');return;}const enabled=await voice.toggle();$('voice').classList.toggle('active',enabled);$('voice').classList.remove('muted');notify(enabled?'🎙️ Voce attiva · senti chi è entro 15 metri':'Voce spenta');}catch(e){notify(e.message);}}
$('voice').onclick=toggleVoice;
function profile(){const box=modal('Il tuo avatar');if(window.HUMANA_3D)box.append(button('🧍 Cambia personaggio 3D',()=>pickLook('Scegli il tuo personaggio',async (i,photo)=>{const u=await api('/look','POST',{look:i,photo});user={...user,avatar:u.avatar};closeModal();notify(photo?'Avatar dalla foto salvato!':'Personaggio: '+LOOKS[i].name);})));const preview=el('canvas');preview.width=140;preview.height=140;preview.getContext('2d').drawImage(renderer.images.avatar,0,0,renderer.images.avatar.width/4,renderer.images.avatar.height/4,0,0,140,140);box.append(preview,el('p',user.username));const form=el('form');const color=el('input');color.type='color';color.value=user.avatar.color;const cl=el('label','Colore personale / cappello');cl.append(color);const acc=el('select');for(const [value,name]of [['none','Senza accessorio'],['cap','Cappello colorato'],['flower','Fiore tra i capelli']]){const option=el('option',name);option.value=value;acc.append(option);}acc.value=user.avatar.accessory;const al=el('label','Accessorio');al.append(acc);const bio=el('textarea');bio.maxLength=160;bio.value=user.bio;const bl=el('label','Qualcosa di te (non inserire dati sensibili)');bl.append(bio);const save=el('button','SALVA AVATAR E PROFILO','primary');save.type='submit';const body=el('select');for(const [value,title] of [['slim','Snella'],['regular','Regolare'],['broad','Robusta']]){const o=el('option',title);o.value=value;body.append(o);}body.value=user.avatar.body||'regular';const bodyLabel=el('label','Corporatura');bodyLabel.append(body);const glasses=el('input');glasses.type='checkbox';glasses.checked=!!user.avatar.glasses;const glassesLabel=el('label','Occhiali');glassesLabel.append(glasses);form.append(cl,al,bodyLabel,glassesLabel,bl,save);form.onsubmit=async e=>{e.preventDefault();try{user=await api('/profile','PATCH',{bio:bio.value,avatar:{color:color.value,accessory:acc.value,body:body.value,glasses:glasses.checked}});closeModal();notify('Profilo salvato');}catch(err){notify(err.message);}};box.append(form);}
$('profile').onclick=profile;
async function social(){const box=modal('Amici e persone vicine');box.append(el('p','Caricamento…'));try{const data=await api('/social');if(!$('modal').open||$('modal-title').textContent!=='Amici e persone vicine')return;box.replaceChildren();box.append(el('h3','Qui nella stanza'));const nearby=players.filter(p=>p.id!==net.id);if(!nearby.length)box.append(el('p','Nessun altro giocatore connesso in questa stanza. Apri un secondo account su un altro browser.','muted'));for(const p of nearby){const row=el('div',undefined,'person');row.append(el('strong',p.username),button('Profilo',()=>showPerson(p)));box.append(row);}box.append(el('h3','Amicizie e richieste'));if(!data.friends.length)box.append(el('p','Le tue richieste appariranno qui.','muted'));for(const f of data.friends){const row=el('div',undefined,'person');row.append(button(f.user.username,()=>showPerson(f.user)),el('small',f.status==='accepted'?(f.online?'Online':'Offline'):'Richiesta in attesa'));if(f.status==='pending'&&f.receiver===net.id)row.append(button('Accetta',async()=>{await api('/friends','POST',{id:f.sender,action:'accept'});social();}));row.append(button(f.status==='accepted'?'Rimuovi':'Annulla / rifiuta',async()=>{await api('/friends','POST',{id:f.user.id,action:'remove'});social();}));box.append(row);}if(data.blocked.length){box.append(el('h3','Bloccati'));for(const p of data.blocked)box.append(button('Sblocca '+p.username,async()=>{await api('/block','POST',{id:p.id,remove:true});social();}));}}catch(e){box.replaceChildren(el('p',e.message));}}
$('friends').onclick=social;
function showPerson(p){if(p.id===net.id)return profile();const box=modal(p.username);box.append(button('📞 Chiama',()=>{closeModal();return calls.start(p);}),button('Messaggio privato',()=>livingUI.conversation(p.id,p.username)),button('Visita appartamento',()=>livingUI.visit(p.id)),button('Invita nel mio appartamento',async()=>{await api('/home/invite','POST',{id:p.id});notify('Invito inviato per un’ora');}));box.append(el('p',p.bio||'Un nuovo incontro sul Lungomare.'),el('small','Posizione: '+MAPS[p.room||'lungomare'].name));box.append(el('br'),button('Aggiungi agli amici',async()=>{await api('/friends','POST',{id:p.id});notify('Richiesta inviata');}),button('Muta / riattiva questa voce',()=>{const muted=!voice.mutedPeers.has(p.id);voice.setPeerMuted(p.id,muted);notify(muted?'Voce di '+p.username+' silenziata':'Voce riattivata');}),button('Blocca',async()=>{await api('/block','POST',{id:p.id});voice.drop(p.id);closeModal();notify('Utente bloccato');}));const reason=el('textarea');reason.placeholder='Motivo della segnalazione';reason.maxLength=500;box.append(reason,button('Invia segnalazione',async()=>{await api('/report','POST',{id:p.id,reason:reason.value});notify('Segnalazione salvata per la moderazione');closeModal();}));}
// Modalità puntatore (PC): clicca sul terreno e il personaggio ci va da solo; il joystick viene nascosto.
const pointer=new PointerMove();let pointerMode=(()=>{try{const v=localStorage.getItem('humana-pointer');return v===null?matchMedia('(pointer:fine)').matches:v==='1';}catch{return false;}})();
function setPointerMode(on){pointerMode=on;document.body.classList.toggle('pointer-mode',on);if(!on)pointer.cancel();try{localStorage.setItem('humana-pointer',on?'1':'0');}catch{}}setPointerMode(pointerMode);
$('world').onclick=e=>{if(!me||$('modal').open)return;if(w3?.suppressClick&&performance.now()-w3.suppressClick<400)return;const p=renderer.hitPlayers.find(p=>Math.hypot(p.x-e.clientX,p.y-e.clientY)<30);if(p){showPerson(players.find(q=>q.id===p.id));return;}if(pointerMode&&!me.seat&&!me.arena){if(!pointer.go(me,renderer.screenToWorld(e.clientX,e.clientY)))notify('Non si può raggiungere quel punto');}};
$('settings').onclick=()=>{const box=modal('Impostazioni e comandi');if(w3&&!w3.toon){const k=w3.avatarKind();box.append(button(k!=='2d'?'🧍 Personaggi: persone realistiche (tocca per le figure disegnate)':'🧍 Personaggi: figure disegnate (tocca per le persone realistiche)',()=>{w3.setAvatarKind(k!=='2d'?'2d':'real');closeModal();notify(k!=='2d'?'Personaggi: figure disegnate':'Personaggi: persone realistiche');}));box.append(button('ℹ️ Crediti dei modelli 3D',()=>{const c=modal('Crediti');for(const t of ['Persone: Microsoft Rocketbox Avatar Library, © 2020 Microsoft, licenza MIT.','Palma da dattero: «Phoenix Palmtree» di gelmi.com.br (sketchfab.com/rodrigogelmi), licenza CC BY 4.0, trasformata in immagini.','Palma nana: «Mediteranean Palm» di BaptisteBerard (sketchfab.com/BaptisteBerard), licenza CC BY 4.0, trasformata in immagini.','Alberi, materiali e cieli: Poly Haven, CC0. Altri modelli: Kenney e Quaternius, CC0.','Elenco completo: /assets/world/napoli/LICENZE.md'])c.append(el('p',null,t));}));}if(hudLayout)box.append(button('🎛️ Sposta i comandi sullo schermo',()=>{closeModal();setTimeout(()=>hudLayout.start(),200);}));box.append(button(pointerMode?'🖱 Modalità puntatore: ATTIVA (clicca per il joystick)':'🕹 Joystick attivo (clicca per la modalità puntatore)',()=>{setPointerMode(!pointerMode);closeModal();notify(pointerMode?'Modalità puntatore: clicca sul terreno per camminare':'Joystick attivo');}));const zoom=el('input');zoom.type='range';zoom.min='.5';zoom.max='1.8';zoom.step='.05';zoom.value=renderer.zoom;zoom.oninput=()=>{renderer.zoom=Number(zoom.value);localStorage.setItem('humana-zoom',zoom.value);};const zl=el('label','Zoom visuale');zl.append(zoom);box.append(zl);const volume=el('input');volume.type='range';volume.min='0';volume.max='1';volume.step='.05';volume.value=voice.volume;volume.oninput=()=>voice.volume=Number(volume.value);const vl=el('label','Volume delle voci vicine');vl.append(volume);box.append(vl,button(voice.muted?'Riattiva microfono':'Muta microfono',()=>{voice.setMuted(!voice.muted);notify(voice.muted?'Microfono muto':'Microfono riattivato');}),...(()=>{const box2=document.createElement('div');box2.className='mic-test';const bar=document.createElement('i'),lab=document.createElement('small');box2.append(lab,bar);let compat=false;try{compat=localStorage.getItem('humana-mic')==='compat'||(!localStorage.getItem('humana-mic')&&/SM-|Samsung/i.test(navigator.userAgent));}catch{}
  const t=setInterval(()=>{if(!document.body.contains(box2)){clearInterval(t);return;}const l=voice.enabled?voice.level():0;bar.style.width=l+'%';lab.textContent=voice.enabled?(voice.muted?'Test microfono: spento (muto)':'Test microfono: parla, la barra deve muoversi ('+l+')'):'Test microfono: attiva prima la voce';},150);
  const sw=button((compat?'✅':'⬜')+' Microfono compatibile (consigliato su Samsung)',async()=>{try{localStorage.setItem('humana-mic',compat?'normal':'compat');}catch{}if(voice.enabled){voice.stop();await toggleVoice();}notify('Impostazione microfono cambiata');$('settings').click();});return [box2,sw];})(),
  button(voice.enabled?'Esci dalla voce (non senti più nessuno)':'Attiva voce',()=>{if(voice.enabled){voice.stop();$('voice').classList.remove('active','muted');notify('Voce spenta');}else toggleVoice();}),el('p','WASD / joystick: movimento. Shift / pulsante Corri tenuto: corsa. E / mano: entra, esci, siediti, alzati. Tocca un avatar per il profilo. La telecamera segue il tuo personaggio.','muted'),el('p','Per la voce su telefono serve HTTPS. Nessuna conversazione viene registrata.','muted'),button('Audio e preferenze salvate',()=>livingUI.audioSettings()),button('ESCI DALL’ACCOUNT',async()=>{await api('/logout','POST',{});setToken('');voice.stop();location.reload();}));};
renderer.zoom=Math.max(.5,Math.min(1.8,Number(localStorage.getItem('humana-zoom'))||1));addEventListener('resize',()=>renderer.resize());
renderer.assetBase=nativeApp?server:'';
// Grafica 3D (prova): si attiva dalle impostazioni o con ?3d=1; all'aperto disegna il mondo in 3D con la telecamera a 360°.
let w3=null;const set3d=async on=>{if(on&&!w3){const {World3D}=await import('./world/world3d.js');w3=new World3D(renderer);
  // Mergellina vera (OpenStreetMap): serve anche qui per prevedere i passi senza attraversare palazzi e mare.
  try{const [{setNapoli},{registerMergellina,registerMallFloor}]=await Promise.all([import('/shared/napoli.js'),import('/shared/world.js')]);registerMallFloor();setNapoli(await (await fetch((renderer.assetBase||'')+'/assets/world/napoli/map/mergellina.json')).json());registerMergellina();}catch(e){console.warn('Mergellina',e);}}if(!on&&w3){w3.show(false);w3=null;location.reload();}};
const want3d=!!window.HUMANA_3D;if(want3d)set3d(true).catch(e=>notify('3D non disponibile: '+e.message));
{const flat=renderer.screenToWorld.bind(renderer);renderer.screenToWorld=(x,y)=>w3?.active?w3.screenToWorld(x,y):flat(x,y);}
// Minimappa: a Mergellina usa l'immagine già pronta del 3D (la mappa 2D è troppo grande da ridisegnare).
// Nel 3D l'immagine della minimappa del Lungomare si tiene da parte: uscendo da un locale non va ridisegnata da capo (era un blocco di un secondo).
let lungoMini=null;const miniMap=(cv,pl,who,size)=>{if(w3&&who?.room==='mergellina')return w3.minimap(cv,pl,who,size);if(w3&&who?.room==='lungomare'&&lungoMini&&renderer.miniCache!==lungoMini)renderer.miniCache=lungoMini;const r=renderer.minimap(cv,pl,who,size);if(w3&&renderer.miniCache?.room==='lungomare')lungoMini=renderer.miniCache;return r;};
let previous=performance.now(),inputClock=0,miniClock=0;
let colSeen=null;setExtraBlock((room,x,y)=>!!w3&&room==='lungomare'&&w3.room==='lungomare'&&w3.blockedStatic(x,y,.35));
function frame(now){const dt=Math.min(.1,(now-previous)/1000);previous=now;arenaUI?.update(me,dt);driveUI?.update(me);w3?.holdCheck?.();if(w3&&w3.col!==colSeen){colSeen=w3.col;resetPaths3d();}let input=controls.input();const use3d=!!(w3&&me&&(me.room==='lungomare'||me.room==='mergellina'||w3.indoor(me.room)));if(use3d)input=w3.worldInput(input);if(me&&window.HUMANA_3D){if(me.fueling||me.consuming||me.jail)input={x:0,y:0,run:false};else if(me.alcohol>6)input=wobbleInput(input,me,now/1000);}if(me){if(input.x||input.y)pointer.cancel();else if(use3d&&w3.hold&&!me.seat&&!$('modal').open){pointer.cancel();const q=renderer.screenToWorld(w3.hold.x,w3.hold.y),dx=q.x-me.x,dy=q.y-me.y,d=Math.hypot(dx,dy);if(d>.6)input={...input,x:dx/d,y:dy/d,run:true};}else{const auto=pointer.input(me,dt);if(auto)input=auto;}renderer.moveTarget=pointer.target;if(use3d&&!me.vehicle&&!me.seat&&(input.x||input.y))input=w3.guard(me,input,step);else if(use3d&&me.vehicle&&!me.seat&&(input.x||input.y)){const hh=Number.isFinite(me.heading)?me.heading:me.direction||0,dd=Math.atan2(input.y,input.x);if(Math.abs(Math.atan2(Math.sin(dd-hh),Math.cos(dd-hh)))>2.2&&!w3.hold)input={...input,rev:true};else if(me.room==='lungomare')input=w3.carGuard(me,input);}inputClock+=dt;if(inputClock>=.05){net.send({type:'input',...input,position:{x:me.x,y:me.y}});inputClock=0;}
 for(const p of display.values()){if(p.id===net.id){step(p,input,dt);const error=Math.hypot(p.targetX-p.x,p.targetY-p.y),walking=input.x||input.y;const gain=error>2?1:walking?(error>.9?1-Math.exp(-4*dt):0):1-Math.exp(-5*dt);p.x+=(p.targetX-p.x)*gain;p.y+=(p.targetY-p.y)*gain;}else{const t=1-Math.exp(-13*dt);p.x+=(p.targetX-p.x)*t;p.y+=(p.targetY-p.y)*t;}}
 if(use3d){w3.show(true);w3.draw([...display.values()],me,dt);renderer.hitPlayers=w3.hit;}else{w3?.show(false);renderer.draw([...display.values()],me,dt);}miniClock+=dt;if(miniClock>.15){miniMap($('minimap'),players,me);if(largeMap&&$('modal').open)miniMap(largeMap,players,me,480);miniClock=0;const door=doors(me.room).find(d=>distance(d,me)<1.65),seat=MAPS[me.room]?.props.find(p=>p.kind==='seat'&&distance(p,me)<1.35);$('nearby-hint').textContent=me.seat==='boat'?'⛵ In barca nel golfo…':me.seat==='bus'?'🚌 In viaggio…':me.seat?'✋ Alzati':door?'✋ '+(door.to==='lungomare'&&me.from?.room==='mergellina'?'Esci a Mergellina':door.name):city.nearby(me)?.label||(seat?'✋ Siediti al tavolo':'');if(!voice.enabled)$('voice').classList.remove('active');}}else if(w3){w3.show(true);w3.autoYaw=false;w3.yaw+=dt*.08;w3.draw([],{id:null,...MAPS.lungomare.spawn,room:'lungomare'},dt);}else renderer.draw([],{id:null,...MAPS.lungomare.spawn,room:'lungomare'},dt);
 if(++frames&&now-lastFps>1000){$('fps').textContent=Math.round(frames*1000/(now-lastFps))+' FPS · prototipo';frames=0;lastFps=now;}requestAnimationFrame(frame);}
renderer.ready.then(async()=>{requestAnimationFrame(frame);await wakeServer();if(token){try{const u=await api('/me');await enter({user:u,token});}catch(e){if(!(e instanceof TypeError))setToken('');}}}).catch(e=>{$('auth-error').textContent=e.message;$('startup-error').hidden=false;$('startup-error-text').textContent=e.message;});

// La minimappa apre una vista ampia: solo navigazione informativa, nessun teletrasporto.
$('minimap').setAttribute('role','button');$('minimap').setAttribute('tabindex','0');$('minimap').setAttribute('aria-label','Apri mappa del quartiere');
// Nel 3D all'aperto: mappa a tutto schermo stile GTA (tocca un punto per andarci).
function openMap(){if(!me)return;if(w3?.active&&MAPS[me.room]&&!me.room.startsWith('home:')){import('./ui/bigmap.js').then(m=>m.openBigMap({me:()=>me,players:()=>players,pointer,w3,notify})).catch(e=>notify(e.message));return;}const box=modal('Mappa del quartiere');const map=el('canvas');largeMap=map;map.style.width='100%';map.style.height='auto';miniMap(map,players,me,480);box.append(map);if(me.room!=='lungomare')return;box.append(el('h3','📍 Dove andare'));const list=el('div',undefined,'poi-list');const icons={bar:'☕',pizzeria:'🍕',shop:'👕',club:'🎵',bank:'🏦',burger:'🍔',osteria:'🍝',vesuvio:'🍷',trattoria:'🍝',panorama:'🍽',mall:'🛍',fashion:'👗',barber:'✂',casino:'🎰'};
 const pois=[...doors('lungomare').filter(d=>icons[d.id]).map(d=>({icon:icons[d.id],name:d.name,x:d.exitX,y:d.exitY})),{icon:'🏖',name:'Spiaggia',x:22,y:9.5},{icon:'🏃',name:'Villa Comunale (pista)',x:115.5,y:29.5},{icon:'🛝',name:'Parco Giochi',x:19,y:112},{icon:'🏡',name:'Le Ville (in vendita)',x:60,y:133},{icon:'🏧',name:'Bancomat',x:114,y:60.6}].map(p=>({...p,d:distance(p,me)})).sort((a,b)=>a.d-b.d);
 for(const p of pois){const row=el('div',undefined,'person');row.append(el('strong',p.icon+' '+p.name),el('small',Math.round(p.d)+' m'+(p.d>60?' · comodo in autobus 🚌':'')),button('Vai',()=>{closeModal();if(pointer.go(me,p))notify('In cammino verso '+p.name);else notify('Percorso non trovato');}));list.append(row);}box.append(list);}
$('minimap').onclick=openMap;$('minimap').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openMap();}};

let recovering=false;
net.addEventListener('reconnecting',e=>{recovering=true;controls.reset();controls.enabled=false;voice.stop();$('connection').textContent='Riconnessione · tentativo '+e.detail;notify('Rete interrotta: tento di riconnetterti mantenendo la posizione.');});
const livingUI=installLivingUI({net,api,modal,button,el,notify,closeModal,renderer,getMe:()=>me,getUser:()=>user,onUser:u=>user=u,voice});
const arenaUI=window.HUMANA_3D?installArena({net,getW3:()=>w3,notify}):null;
// HUMANA life 3D: la chat non sta più sempre aperta davanti alla visuale; si apre col bottone «Chat» del menu di sinistra (pannello a lato) e si chiude con ✕, col bottone o con Esc.
if(window.HUMANA_3D){const tg=$('chat-toggle'),box=$('chat');if(tg&&box){const x=el('button','','✕');x.type='button';x.className='chat-x';x.setAttribute('aria-label','Chiudi la chat');box.prepend(x);const set=on=>{document.body.classList.toggle('chat-open',on);if(on){tg.dataset.n='0';const m=$('messages');if(m)m.scrollTop=m.scrollHeight;setTimeout(()=>$('chat-input')?.focus(),60);}else document.activeElement?.blur?.();};tg.onclick=()=>set(!document.body.classList.contains('chat-open'));x.onclick=()=>set(false);addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('chat-open'))set(false);else if(e.key==='Enter'&&!document.body.classList.contains('chat-open')&&!document.activeElement?.closest?.('input,textarea')&&!$('modal').open&&me)set(true);});}}
const driveUI=window.HUMANA_3D?installDriveHud({api,net,notify}):null;
const hudLayout=window.HUMANA_3D?installHudLayout({notify}):null;
// Tasto indietro di Android (e gesto): chiude il telefono o la finestra aperta invece di uscire dal gioco.
if(window.HUMANA_3D){try{history.pushState({hb:1},'');}catch{}addEventListener('popstate',()=>{try{window.humanaBack?.();history.pushState({hb:1},'');}catch{}});}
const city=installCity({net,api,modal,button,el,notify,closeModal,getMe:()=>me,getW3:()=>w3,renderer,getUser:()=>user,onUser:u=>{user=u;document.dispatchEvent(new CustomEvent('humana:avatar'));}});
if(/^(localhost|127.0.0.1)$/.test(location.hostname))window.__city=city;
const jobs=installJobs({api,net,notify,modal,button,getMe:()=>me,renderer});
installHUD({jobs,city,net,api,renderer,livingUI,modal,button,el,notify,profile,social,openMap,toggleVoice,getUser:()=>user,getMe:()=>me,calls,setControls:on=>{controls.reset();controls.enabled=on&&!!me&&!$('modal').open;}});

// Installazione PWA disponibile su HTTPS o localhost; nessuna sessione simulata offline.
if('serviceWorker' in navigator&&isSecureContext)navigator.serviceWorker.register('/sw.js').then(reg=>{const offer=()=>{if(!reg.waiting)return;const box=modal('Aggiornamento HUMANA disponibile');box.append(el('p','È pronta una versione aggiornata della mappa e dei comandi. La posizione viene salvata dal server.'),button('Aggiorna e riapri',()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});reg.waiting.postMessage({type:'APPLY_UPDATE'});}));};if(reg.waiting)offer();reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)offer();});});}).catch(e=>notify('Cache offline non disponibile: '+e.message));
addEventListener('offline',()=>notify('Sei offline. Il mondo riprenderà quando il server sarà raggiungibile.'));

// Modalità ispezione per segnalare bug (pulsante 🔍, F2 o ?ispeziona=1): personaggio fermo, telecamera libera su tutta la mappa,
// clic su un elemento o su un punto → segnalazione salvata nel progetto (data/segnalazioni) con ritaglio dello schermo.
{const layer=document.createElement('div');layer.id='inspect-layer';document.body.append(layer);let on=false;
 const tick=()=>{layer.hidden=!on;if(on)renderer.inspect(layer);};setInterval(tick,300);
 const btn=document.createElement('button');btn.id='inspect-toggle';btn.type='button';btn.textContent='🔍 Ispeziona';
 const panel=document.createElement('form');panel.id='report-panel';panel.hidden=true;panel.innerHTML='<b>Segnala a Claude</b><div class="rp-what"></div><img alt="ritaglio"><textarea maxlength="2000" placeholder="Cosa non va? (es. storto, si blocca, non si apre…)"></textarea><div class="rp-row"><button type="submit">📨 Invia a Claude</button><button type="button" class="rp-x">Annulla</button></div>';document.body.append(panel);
 let pending=null;const what=panel.querySelector('.rp-what'),img=panel.querySelector('img'),txt=panel.querySelector('textarea');
 const crop=(sx,sy)=>{try{const c=renderer.canvas,d=renderer.dpr||1,S=360,o=document.createElement('canvas');o.width=S;o.height=S*.7;o.getContext('2d').drawImage(c,(sx-S/2)*d,(sy-S*.35)*d,S*d,S*.7*d,0,0,S,S*.7);const g=o.getContext('2d');g.strokeStyle='#ff2d55';g.lineWidth=3;g.beginPath();g.arc(S/2,S*.35,14,0,7);g.stroke();return o.toDataURL('image/png');}catch{return null;}};
 const ask=(label,sx,sy)=>{const w=renderer.screenToWorld(sx,sy);pending={label,x:w.x,y:w.y,room:me?.room||'',zoom:renderer.viewZoom,image:crop(sx,sy)};what.textContent=label+' · x '+w.x.toFixed(1)+' y '+w.y.toFixed(1);img.src=pending.image||'';panel.hidden=false;txt.value='';txt.focus();};
 panel.querySelector('.rp-x').onclick=()=>{panel.hidden=true;pending=null;};
 panel.onsubmit=async e=>{e.preventDefault();if(!pending)return;try{const r=await fetch(server+'/api/segnala',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+sessionStorage.getItem('humana-token')},body:JSON.stringify({...pending,note:txt.value})});const j=await r.json();if(!r.ok)throw new Error(j.error);notify('📨 Segnalazione inviata a Claude');panel.hidden=true;pending=null;}catch(err){notify('Invio non riuscito: '+err.message);}};
 // Clic: sul riquadro di un elemento → quell'elemento; sul vuoto → il punto della mappa. Trascina per spostare la vista, rotellina per lo zoom.
 let drag=null;layer.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:renderer.freeCam.x,cy:renderer.freeCam.y,moved:false};layer.setPointerCapture(e.pointerId);});
 layer.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;const z=renderer.viewZoom||1;renderer.freeCam={x:drag.cx-dx/z,y:drag.cy-dy/z};});
 layer.addEventListener('pointerup',e=>{const d=drag;drag=null;if(!d||d.moved)return;layer.releasePointerCapture?.(e.pointerId);layer.hidden=true;const el=document.elementFromPoint(e.clientX,e.clientY);layer.hidden=false;const hit=[...layer.children].find(b=>{const r=b.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;});ask(hit?hit.dataset.label:'Punto della mappa',e.clientX,e.clientY);});
 layer.addEventListener('wheel',e=>{e.preventDefault();renderer.freeZoom=Math.min(1.6,Math.max(.22,(renderer.freeZoom||1)*(e.deltaY>0?.88:1.14)));},{passive:false});
 addEventListener('keydown',e=>{if(!on||e.target.tagName==='TEXTAREA')return;const k={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]}[e.key];if(k){const st=60/(renderer.viewZoom||1);renderer.freeCam={x:renderer.freeCam.x+k[0]*st,y:renderer.freeCam.y+k[1]*st};e.preventDefault();}});
 const set=v=>{on=v;btn.classList.toggle('on',on);btn.textContent=on?'🔍 Ispezione ON · clicca per segnalare':'🔍 Ispeziona';
  if(on){controls.reset();controls.enabled=false;renderer.freeCam={...renderer.camera};renderer.freeZoom=renderer.zoom;notify('🔍 Personaggio fermo. Trascina per muovere la vista, rotellina per lo zoom, clicca un punto per segnalarlo.');}
  else{renderer.freeCam=null;controls.enabled=!$('modal').open;panel.hidden=true;}tick();};
 btn.onclick=()=>set(!on);btn.hidden=true;document.body.append(btn);net.addEventListener('welcome',async()=>{try{const r=await api('/map/edits');btn.hidden=!r.admin;if(!r.admin&&on)set(false);}catch{btn.hidden=true;}});
 addEventListener('keydown',e=>{if(e.key==='F2'&&!btn.hidden)set(!on);});if(new URLSearchParams(location.search).has('ispeziona'))setTimeout(()=>{if(!btn.hidden)set(true);},4000);}

// Le modifiche fatte dagli admin (pagina /admin) arrivano in tempo reale e aggiornano mappa e percorsi.
net.addEventListener('mapEdits',e=>{renderer.noNpc=e.detail.doc?.settings?.npc===false;applyMapEdits(e.detail.doc);resetPaths();renderer.chunks.clear();renderer.miniCache=null;});

// Aggiornamento inviato dall'admin: si ricarica e prende la versione nuova dal server (anche nell'app Android).
net.addEventListener('appUpdate',()=>{notify('⬆️ Aggiornamento in corso…');setTimeout(()=>location.reload(),1200);});

// Zoom della visuale: due dita sul telefono (allarga = avvicina, stringi = allontana) e rotellina sul PC. Il valore resta salvato.
{const canvas=$('world'),clampZ=z=>Math.min(1.8,Math.max(.5,z)),save=()=>{try{localStorage.setItem('humana-zoom',String(renderer.zoom));}catch{}};
 let pinch=null;const dist=t=>Math.hypot(t[0].clientX-t[1].clientX,t[0].clientY-t[1].clientY);
 canvas.addEventListener('touchstart',e=>{if(e.touches.length===2){pinch={d:dist(e.touches),z:renderer.zoom};e.preventDefault();}},{passive:false});
 canvas.addEventListener('touchmove',e=>{if(pinch&&e.touches.length===2){renderer.zoom=clampZ(pinch.z*dist(e.touches)/pinch.d);e.preventDefault();}},{passive:false});
 canvas.addEventListener('touchend',e=>{if(pinch&&e.touches.length<2){pinch=null;save();}});
 canvas.addEventListener('wheel',e=>{if(renderer.freeCam)return;if(w3?.active&&!e.ctrlKey&&!(e.deltaX===0&&Math.abs(e.deltaY)>=50&&e.deltaMode===0&&Number.isInteger(e.deltaY))&&e.deltaMode===0){e.preventDefault();w3.autoYaw=false;w3.yaw-=e.deltaX*.005;w3.pitch=Math.max(-.6,Math.min(.6,w3.pitch-e.deltaY*.003));return;}e.preventDefault();renderer.zoom=clampZ(renderer.zoom*(e.deltaY>0?.9:1.1));save();},{passive:false});}
