// Guida e bevute (solo HUMANA life 3D): indicatore della benzina, bottone «Scendi» quando si è su un mezzo, barra dell'alcol e leggero velo quando si è brilli.
import {VEHICLE,FUEL,HEISTS,HEIST_TIERS} from '/shared/catalog.js';
const baseOf=id=>VEHICLE[id]?.base||id;
// Ubriachi si cammina storti: un po' di oscillazione sul movimento scelto (l'avatar e la telecamera ondeggiano da soli nel mondo 3D).
export function wobbleInput(input,me,t){const a=Math.min(1,(me.alcohol||0)/100);if(!input||!(input.x||input.y))return input;const w=.55*a;return {...input,x:input.x+Math.sin(t*1.9)*w,y:input.y+Math.cos(t*1.35)*w};}
export function installDriveHud({api,net,notify}){
 const root=document.createElement('div');root.innerHTML='<div id="drive-hud" hidden><div class="dh-fuel"><span>⛽</span><div class="dh-bar"><i></i></div><b>100%</b></div><button type="button" class="dh-horn" aria-label="Clacson">📯 Clacson</button><button type="button" class="dh-off">⬇ Scendi</button></div><div id="alc-hud" hidden><span>🍺 Alcol</span><div class="dh-bar alc"><i></i></div><b>0%</b></div><div id="drunk-veil"></div><button type="button" id="steal-btn" aria-pressed="false" aria-label="Ruba">🤫<small>NO</small></button><button type="button" id="heist-btn" hidden></button><div id="heist-hud" hidden><b></b><div class="dh-bar"><i></i></div></div><div id="broken-hud" hidden><b>🔧 Guasto: il mezzo non parte</b><button type="button">📞 Chiama il meccanico</button></div><div id="down-hud" hidden><b></b><button type="button">📞 Chiama il 118</button></div><div id="wanted-hud" hidden></div><div id="jail-hud" hidden><div class="jh-box"><div class="jh-bars">▮▮▮▮▮▮▮▮</div><h2>🚔 Sei in prigione</h2><p>Hai preso senza pagare e un agente ti ha visto.</p><p class="jh-t"></p><small>Poi un agente viene a liberarti.</small></div></div>';
 document.body.append(...root.children);
 const $=s=>document.querySelector(s),dh=$('#drive-hud'),alc=$('#alc-hud'),veil=$('#drunk-veil'),off=$('.dh-off');let meNow=null,busy=false;
 const sb=$('#steal-btn');sb.style.display='none';/* il bottone Ruba si vede solo in partita, non sulla schermata d'accesso né nel menu iniziale */const wh=$('#wanted-hud'),jh=$('#jail-hud');sb.onclick=()=>{globalThis.__steal=!globalThis.__steal;sb.innerHTML='🤫<small>'+(globalThis.__steal?'SÌ':'NO')+'</small>';sb.classList.toggle('on',!!globalThis.__steal);sb.setAttribute('aria-pressed',String(!!globalThis.__steal));notify(globalThis.__steal?'🤫 Modalità furto: quello che prendi non lo paghi… ma se ti vedono vai in prigione!':'Torni onesto: si paga di nuovo');};
 // Rapine (stile FiveM): con la modalità furto accesa, dentro un locale rapinabile compare «💰 Rapina»; durante il colpo una barra conta i secondi.
 const hb=$('#heist-btn'),hh=$('#heist-hud');if(net&&!net.__rpWallet){net.__rpWallet=true;net.addEventListener('wallet',()=>document.dispatchEvent(new CustomEvent('humana:wallet')));}
 hb.onclick=async()=>{if(busy)return;busy=true;try{await api('/heist/start','POST',{});}catch(e){notify(e.message);}finally{setTimeout(()=>busy=false,600);}};
 // Feriti: a terra compare la scritta col tempo che resta e il bottone per chiamare il 118.
 const bk=$('#broken-hud');bk.querySelector('button').onclick=async()=>{try{await api('/rp/callmech','POST',{});}catch(e){notify(e.message);}};
 const dn=$('#down-hud');dn.querySelector('button').onclick=async()=>{try{await api('/rp/call118','POST',{});}catch(e){notify(e.message);}};
 const horn=$('.dh-horn');const honk=()=>{if(!meNow?.vehicle||meNow.seat)return;window.humanaHorn?.();net.send({type:'horn'});};horn.onclick=honk;addEventListener('keydown',e=>{if((e.key==='h'||e.key==='H')&&!/INPUT|TEXTAREA/.test(document.activeElement?.tagName||''))honk();});
 off.onclick=async()=>{if(busy)return;busy=true;try{if(meNow?.seat==='car')net.send({type:'interact'});else{await api('/vehicle/use','POST',{});}}catch(e){notify(e.message);}finally{setTimeout(()=>busy=false,500);}};
 return {update(me){meNow=me||null;const showSb=!!me&&!$('#hud')?.hidden;if((sb.style.display!=='none')!==showSb)sb.style.display=showSb?'':'none';if(sb.parentElement?.id!=='cam3d'){const c=document.querySelector('#cam3d');if(c)c.append(sb);}const v=me?.vehicle,motor=!!v&&FUEL.motor.includes(baseOf(v)),pass=me?.seat==='car';dh.hidden=!(v||pass);if(v||pass){
   const f=$('.dh-fuel');f.hidden=!motor;if(motor){let lvl=me.fuel??FUEL.tank;if(me.fueling){const k=Math.min(1,(Date.now()-me.fueling.t0)/(me.fueling.until-me.fueling.t0));lvl=lvl+(FUEL.tank-lvl)*k;}const i=f.querySelector('i');i.style.width=Math.max(0,Math.min(100,lvl))+'%';i.style.background=lvl<=FUEL.low?'#ef4444':lvl<50?'#f5b83d':'#35d07f';f.querySelector('b').textContent=Math.round(lvl)+'%';f.classList.toggle('low',lvl<=FUEL.low);}
   off.hidden=!!me.fueling;horn.hidden=!(v&&!me.fueling&&['auto','cabrio','furgone','scooter'].includes(baseOf(v)));}
  const jail=me?.jail;jh.hidden=!jail;if(jail)jh.querySelector('.jh-t').textContent='Liberazione tra '+Math.max(0,Math.ceil((jail.until-Date.now())/1000))+' secondi';wh.hidden=!(me?.wanted)||!!jail;if(me?.wanted)wh.textContent='🚨 RICERCATO: gli agenti ti cercano…';
  const brk=!!me?.broken&&!!me?.vehicle;if(bk.hidden!==!brk)bk.hidden=!brk;
  const down=me?.down;if(dn.hidden!==!down)dn.hidden=!down;if(down)dn.querySelector('b').textContent='😵 Sei a terra. Un paramedico può rianimarti · ospedale tra '+Math.max(0,Math.ceil((down.until-Date.now())/1000))+' s';
  const tier=me&&HEIST_TIERS[HEISTS[me.room]],rob=!!tier&&!!globalThis.__steal&&!me.heist&&!jail&&!me.wanted&&!me.vehicle&&!me.seat&&!(me.work==='polizia'&&me.duty)&&!$('#hud')?.hidden;
  if(hb.hidden!==!rob)hb.hidden=!rob;if(rob&&hb.dataset.r!==me.room){hb.dataset.r=me.room;hb.textContent='💰 Rapina '+tier.label+' ('+tier.sec+' s)';}
  const hs=me?.heist;if(hh.hidden!==!hs)hh.hidden=!hs;if(hs){const left=Math.max(0,hs.until-Date.now()),k=1-left/Math.max(1,hs.until-hs.t0);hh.querySelector('b').textContent='💰 Rapina a '+hs.name+': resta dentro! '+Math.ceil(left/1000)+' s';hh.querySelector('i').style.width=Math.round(Math.min(1,Math.max(0,k))*100)+'%';}
  const a=me?.alcohol||0;alc.hidden=a<=.5;if(a>.5){alc.querySelector('i').style.width=Math.min(100,a)+'%';alc.querySelector('b').textContent=Math.round(a)+'%';}veil.style.opacity=a>6?String(Math.min(.8,a/100)):'0';}};
}
