import {AmbientAudio} from '../audio/ambient.js';
export function installLivingUI(ctx){
 const {net,api,modal,button,el,notify,closeModal,renderer,getMe,getUser,onUser,voice}=ctx;
 const sound=new AmbientAudio();let current=null,settings=null;
 async function load(){current=await api('/state');settings={master:.6,music:.6,ambient:.6,voice:.6,zoom:1,...current.settings};renderer.zoom=settings.zoom;voice.volume=settings.voice*settings.master;sound.settings=settings;document.dispatchEvent(new CustomEvent('humana:wallet',{detail:current}));return current;}
 function menu(){const box=modal('La tua vita in '+(window.HUMANA_3D?'Napoli life':'HUMANA'));box.append(button('Inventario e negozio',inventory),button('Ordina nel locale',orders),button('Il mio appartamento',home),button('Messaggi privati',inbox),button('Eventi sociali',events),button('Audio e preferenze',audioSettings),button('Premio passeggiata · 100 m',async()=>{current=await api('/reward','POST',{});notify('30 monete e 1 gemma aggiunte');}));}
 async function inventory(){await load();const box=modal('Inventario · '+current.balance+' monete');box.append(el('p','Valuta virtuale non convertibile. Acquista nella Bottega Marina. I cosmetici posseduti si equipaggiano ovunque.','muted'));
  for(const item of current.catalog.filter(i=>i.type!=='food')){const owned=current.inventory.find(i=>i.item===item.id)?.quantity||0;const row=el('div',undefined,'person');row.append(el('strong',item.name),el('small',`${item.price} ${item.currency==='gems'?'gemme':'monete'} · posseduti: ${owned}`));row.append(button('Acquista',async()=>{await api('/purchase','POST',{item:item.id,requestId:crypto.randomUUID()});await inventory();}));if(item.type==='cosmetic'&&owned)row.append(button('Equipaggia',async()=>{const avatar=await api('/equip','POST',{item:item.id});onUser({...getUser(),avatar});notify('Oggetto equipaggiato');}));box.append(row);}
 }
 async function orders(){await load();const room=getMe()?.room;const box=modal('Menu del locale');const items=current.catalog.filter(i=>i.type==='food'&&i.room===room);if(!items.length)box.append(el('p','Entra nel bar o nella pizzeria per ordinare.'));for(const item of items)box.append(button(`${item.name} · ${item.price} monete`,async()=>{const result=await api('/purchase','POST',{item:item.id,requestId:crypto.randomUUID()});notify('Ordine servito: '+item.name+' · saldo '+result.balance);await orders();}));}
 async function home(){await load();const box=modal('Il tuo appartamento');box.append(button('Entra in casa',()=>visit(getUser().id)));const privacy=el('select');for(const value of ['PRIVATE','FRIENDS','PUBLIC']){const o=el('option',({PRIVATE:'Solo io e invitati',FRIENDS:'Amici e invitati',PUBLIC:'Pubblico'})[value]);o.value=value;privacy.append(o);}privacy.value=current.home.privacy;box.append(privacy,button('Salva privacy',async()=>{await api('/home','PATCH',{privacy:privacy.value});notify('Privacy aggiornata; inviti precedenti revocati');}),button('Arreda appartamento',decorate),el('p','Dal profilo di un amico puoi invitarlo per un’ora. Le residenze in strada rimangono esterni decorativi; questo pulsante apre la tua stanza personale.','muted'));}
 async function visit(owner){await api('/home/enter','POST',{owner});closeModal();}
 async function decorate(){await load();const box=modal('Disponi gli arredi');let furniture=JSON.parse(current.home.furniture);const select=el('select');for(const owned of current.inventory){const item=current.catalog.find(i=>i.id===owned.item&&i.type==='furniture');if(item){const o=el('option',item.name+' · '+owned.quantity);o.value=item.id;select.append(o);}}
  if(!select.options.length){box.append(el('p','Acquista prima un arredo in negozio.'));return;}
  const canvas=el('canvas');canvas.width=480;canvas.height=336;canvas.style.width='100%';canvas.style.touchAction='none';const draw=()=>{const c=canvas.getContext('2d');c.fillStyle='#b38b68';c.fillRect(0,0,480,336);c.strokeStyle='#e2c29b';for(let x=0;x<16;x++)for(let y=0;y<14;y++)c.strokeRect(x*30,y*24,30,24);c.fillStyle='#f3e8bd';c.fillRect(210,288,60,48);for(const f of furniture){c.fillStyle='#123b49';c.beginPath();c.arc(f.x*30,f.y*24,8,0,7);c.fill();c.font='11px sans-serif';c.fillText(current.catalog.find(i=>i.id===f.item)?.name||f.item,f.x*30+10,f.y*24);}};
  canvas.onclick=e=>{const b=canvas.getBoundingClientRect();furniture.push({item:select.value,x:Math.round((e.clientX-b.x)/b.width*32)/2,y:Math.round((e.clientY-b.y)/b.height*28)/2});draw();};draw();box.append(select,el('p','Tocca la pianta per posare l’oggetto. Lascia libera la fascia dell’ingresso in basso.','muted'),canvas,button('Rimuovi ultimo',()=>{furniture.pop();draw();}),button('Salva disposizione',async()=>{await api('/home','PATCH',{furniture});notify('Arredamento salvato');closeModal();}));
 }
 async function conversation(id,name){const messages=await api('/dm?peer='+encodeURIComponent(id));const box=modal('Messaggi · '+name);const list=el('div');for(const m of messages)list.append(el('p',m.username+': '+m.text));const input=el('textarea');input.maxLength=500;input.placeholder='Scrivi un messaggio privato';box.append(list,input,button('Invia',async()=>{await api('/dm','POST',{id,text:input.value});await conversation(id,name);}));}
 async function inbox(){const messages=await api('/inbox');const box=modal('Messaggi ricevuti');if(!messages.length)box.append(el('p','Nessun messaggio. Apri il profilo di una persona per scriverle.'));for(const m of messages)box.append(button(m.username+': '+m.text.slice(0,60),()=>conversation(m.sender,m.username)));}
 async function events(){const rows=await api('/events');const box=modal('Eventi della community');for(const event of rows){const row=el('div',undefined,'person');row.append(el('strong',event.name),el('p',new Date(event.start_time).toLocaleString()+' · '+event.location),button('Partecipa',async()=>{await api('/events/join','POST',{id:event.id});notify('Partecipazione salvata. Raggiungi il luogo indicato.');}));box.append(row);}if(!rows.length)box.append(el('p','Nessun evento futuro. Puoi organizzare il primo.'));box.append(button('Organizza evento',()=>{const form=modal('Nuovo evento');const name=el('input');name.placeholder='Titolo';name.maxLength=60;const date=el('input');date.type='datetime-local';const location=el('select');for(const [id,label]of [['club','Discoteca'],['lungomare','Piazza'],['home:'+getUser().id,'Il mio appartamento']]){const o=el('option',label);o.value=id;location.append(o);}form.append(name,date,location,button('Crea evento di un’ora',async()=>{const start=new Date(date.value).getTime();await api('/events','POST',{name:name.value,location:location.value,start_time:start,end_time:start+3600000});await events();}));}));}
 async function audioSettings(){await load();const box=modal('Audio e preferenze');box.append(button(sound.enabled?'Spegni ambiente e musica':'Attiva ambiente e musica',async()=>{if(sound.enabled){sound.stop();try{localStorage.setItem('humana-audio','off');}catch{}}else{await sound.start();try{localStorage.removeItem('humana-audio');}catch{}}await audioSettings();}));for(const key of ['master','music','ambient','voice']){const label=el('label',({master:'Generale',music:'Musica',ambient:'Ambiente',voice:'Voce'})[key]);const slider=el('input');slider.type='range';slider.min=0;slider.max=1;slider.step=.05;slider.value=settings[key];slider.oninput=()=>{settings[key]=Number(slider.value);sound.settings=settings;voice.volume=settings.voice*settings.master;};label.append(slider);box.append(label);}box.append(button('Salva preferenze',async()=>{settings.zoom=renderer.zoom;await api('/settings','PATCH',settings);notify('Preferenze salvate sul server');}));}
 // Musica e ambiente partono al primo gesto (regola dei browser), salvo se il giocatore li ha spenti.
 {const go=()=>{let off=false;try{off=localStorage.getItem('humana-audio')==='off';}catch{}if(!off&&!sound.enabled)sound.start().catch(()=>{});removeEventListener('pointerdown',go);removeEventListener('keydown',go);};addEventListener('pointerdown',go);addEventListener('keydown',go);}
 net.addEventListener('state',e=>{const me=e.detail.players.find(p=>p.id===net.id);if(me)sound.update(me);});
 net.addEventListener('disconnected',()=>sound.stop());net.addEventListener('reconnecting',()=>sound.stop());
 net.addEventListener('notification',e=>{notify(e.detail.message);if(e.detail.home){const box=modal('Invito in appartamento');box.append(el('p',e.detail.message),button('Accetta ed entra',()=>visit(e.detail.home)));}});
 return {load,conversation,visit,audioSettings,inventory,home,inbox,events,menu};
}
