export class Controls{
 constructor(joystick,run,interact){this.keys=new Set();this.vector={x:0,y:0};this.running=false;this.pointer=null;this.enabled=true;this.runPointer=null;
 const typing=()=>['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);
 addEventListener('keydown',e=>{if(typing()||!this.enabled)return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','ShiftLeft','ShiftRight','KeyE'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)interact();});addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('blur',()=>this.reset());document.addEventListener('focusin',()=>{if(typing())this.reset();});document.addEventListener('visibilitychange',()=>{if(document.hidden)this.reset();});
 const move=e=>{const r=joystick.getBoundingClientRect();let x=(e.clientX-r.x-r.width/2)/(r.width*.32),y=(e.clientY-r.y-r.height/2)/(r.height*.32);let len=Math.max(1,Math.hypot(x,y));x/=len;y/=len;this.vector={x,y};joystick.firstElementChild.style.transform=`translate(${x*r.width*.24}px,${y*r.width*.24}px)`;};
 joystick.onpointerdown=e=>{if(!this.enabled||this.pointer!==null)return;this.pointer=e.pointerId;joystick.setPointerCapture(e.pointerId);move(e);};joystick.onpointermove=e=>{if(e.pointerId===this.pointer)move(e);};const release=e=>{if(e.pointerId!==this.pointer)return;this.pointer=null;this.vector={x:0,y:0};joystick.firstElementChild.style.transform='';};joystick.onpointerup=release;joystick.onpointercancel=release;joystick.onlostpointercapture=release;
 run.onpointerdown=e=>{if(!this.enabled)return;this.runPointer=e.pointerId;run.setPointerCapture(e.pointerId);this.running=true;run.classList.add('active');};const stop=e=>{if(e.pointerId===this.runPointer){this.running=false;this.runPointer=null;run.classList.remove('active');}};run.onpointerup=stop;run.onpointercancel=stop;run.onlostpointercapture=stop;
 this.joystick=joystick;this.runButton=run;
 }
 reset(){this.keys.clear();this.vector={x:0,y:0};this.running=false;this.pointer=null;this.runPointer=null;if(this.joystick)this.joystick.firstElementChild.style.transform='';this.runButton?.classList.remove('active');}
 input(){if(!this.enabled)return{x:0,y:0,run:false};const sx=this.vector.x+((this.keys.has('KeyD')||this.keys.has('ArrowRight'))?1:0)-((this.keys.has('KeyA')||this.keys.has('ArrowLeft'))?1:0),sy=this.vector.y+((this.keys.has('KeyS')||this.keys.has('ArrowDown'))?1:0)-((this.keys.has('KeyW')||this.keys.has('ArrowUp'))?1:0);return{x:(sx+sy)/Math.SQRT2,y:(sy-sx)/Math.SQRT2,run:this.running||this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')};}
}
