import {CATALOG as BASE_CATALOG,WEAR_ITEMS,WEAR,HAIR_STYLES,BEARD_STYLES,HAIR_COLORS,BARBER_PRICE,cleanSettings,SHOP_ROOMS,ATM_RATE,VILLA_PRICE,VILLA_RENT,VILLA_RENT_DAYS,DAILY_FICHES,SLOT_BETS,SLOT_SYMBOLS,VEHICLES,VEHICLE,DRINKS,JUKEBOX,JUKEBOX_PRICE,JUKEBOX_MINUTES,DEALERS,VEHICLES_3D,BOATS,FUNFAIR,ridePlan,BOAT_PRICE,BOAT_SPEED} from '../shared/catalog.js';
import {randomInt} from 'node:crypto';
import {MAPS,canStand,distance} from '../shared/world.js';
import {state,ensureState,savePlayer} from './storage.js';
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const CATALOG=BASE_CATALOG;const ITEMS=new Map([...BASE_CATALOG,...WEAR_ITEMS].map(i=>[i.id,i]));
export class Living{
 constructor(db,game){this.db=db;this.game=game;this.lastDM=new Map();}
 friends(a,b){return !!this.db.prepare("SELECT 1 FROM friendships WHERE status='accepted' AND ((sender=? AND receiver=?) OR (sender=? AND receiver=?))").get(a,b,b,a);}
 homeAllowed(owner,guest){if(owner===guest)return true;if(this.game.blocked(owner,guest))return false;const home=this.db.prepare('SELECT privacy FROM homes WHERE owner=?').get(owner);return home&&(home.privacy==='PUBLIC'||home.privacy==='FRIENDS'&&this.friends(owner,guest)||!!this.db.prepare('SELECT 1 FROM home_invites WHERE owner=? AND guest=? AND expires>?').get(owner,guest,Date.now()));}
 homeMap(owner){const home=this.db.prepare('SELECT * FROM homes WHERE owner=?').get(owner);if(!home)return null;const id='home:'+owner;const props=JSON.parse(home.furniture).map(f=>({...f,kind:CATALOG.find(i=>i.id===f.item)?.kind||'plant',r:f.item==='table'?.6:f.item==='bed'||f.item==='sofa'?.8:.25}));return MAPS[id]={id,name:'Appartamento',bounds:{x:0,y:0,w:16,h:14},spawn:{x:8,y:12},buildings:[],props};}
 snapshot(id){const s=state(this.db,id);return {level:1+Math.floor((s.progress.xp||0)/100),xp:Math.floor(s.progress.xp||0),vip:(s.progress.xp||0)>=500,gems:s.progress.gems||0,balance:s.balance,settings:s.settings,progress:s.progress,walked:s.walked,inventory:s.inventory,home:this.db.prepare('SELECT privacy,furniture FROM homes WHERE owner=?').get(id),catalog:CATALOG};}
 move(p,room){p.room=room;Object.assign(p,MAPS[room].spawn);p.input={x:0,y:0};p.seat=null;p.voice=false;p.talking=false;savePlayer(this.db,p);}
 purchase(id,body){
  const item=ITEMS.get(body.item);if(!item||typeof body.requestId!=='string'||!/^[a-zA-Z0-9_-]{8,80}$/.test(body.requestId))fail('Acquisto non valido');
  const old=this.db.prepare('SELECT result FROM purchases WHERE user_id=? AND request_id=?').get(id,body.requestId);if(old)return JSON.parse(old.result);
  const p=this.game.players.get(id);if(!p)fail('Entra nel mondo prima di acquistare');if(item.room&&p.room!==item.room)fail('Ordina nel locale corretto');if(item.type==='wear'&&p.room!=='fashion'&&!((p.room==='mall'||p.room==='mall2')&&this.edition==='3d'))fail('I vestiti si comprano al Moda Market');if(item.type!=='food'&&item.type!=='wear'&&!SHOP_ROOMS.includes(p.room)&&!(body.online===true&&this.edition==='3d'))fail('Gli acquisti si fanno nella Bottega Marina o nel Centro Commerciale');
  ensureState(this.db,id);this.db.exec('BEGIN IMMEDIATE');try{
   if((item.type==='cosmetic'||item.type==='wear')&&this.db.prepare('SELECT 1 FROM inventory WHERE user_id=? AND item=?').get(id,item.id))fail('Possiedi già questo cosmetico');
   if(item.currency==='gems'){
    const changed=this.db.prepare("UPDATE player_state SET progress=json_set(progress,'$.gems',coalesce(json_extract(progress,'$.gems'),0)-?) WHERE user_id=? AND coalesce(json_extract(progress,'$.gems'),0)>=?").run(item.price,id,item.price).changes;
    if(!changed)fail('Gemme insufficienti');
   }else if(!this.db.prepare('UPDATE player_state SET balance=balance-? WHERE user_id=? AND balance>=?').run(item.price,id,item.price).changes)fail('Monete insufficienti');
   if(item.type!=='food')this.db.prepare('INSERT INTO inventory VALUES(?,?,1) ON CONFLICT(user_id,item) DO UPDATE SET quantity=quantity+1').run(id,item.id);
   else{const row=state(this.db,id);row.progress.orders=(row.progress.orders||0)+1;this.db.prepare('UPDATE player_state SET progress=? WHERE user_id=?').run(JSON.stringify(row.progress),id);}
   const result={ok:true,item:item.id,balance:this.db.prepare('SELECT balance FROM player_state WHERE user_id=?').get(id).balance};this.db.prepare('INSERT INTO purchases VALUES(?,?,?)').run(id,body.requestId,JSON.stringify(result));this.db.exec('COMMIT');return result;
  }catch(e){this.db.exec('ROLLBACK');throw e;}
 }
 // Mobilità: pagamento atomico in monete, mezzi posseduti e noleggi a scadenza.
 pay(id,amount){if(!this.db.prepare('UPDATE player_state SET balance=balance-? WHERE user_id=? AND balance>=?').run(amount,id,amount).changes)fail('Monete insufficienti');}
 canUse(id,vid){const g=state(this.db,id).progress;return (g.vehicles||[]).includes(vid)||(g.rentals?.[vid]||0)>Date.now();}
 // Al rientro si riprende il mezzo usato per ultimo, se ancora valido.
 lastVehicle(id){const v=state(this.db,id).progress.activeVehicle;return v&&this.canUse(id,v)?v:null;}
 garage(id){const g=state(this.db,id).progress,p=this.game.players.get(id);return {balance:this.db.prepare('SELECT balance FROM player_state WHERE user_id=?').get(id).balance,active:p?.vehicle||null,vehicles:[...VEHICLES,...VEHICLES_3D.filter(v=>(g.vehicles||[]).includes(v.id))].map(v=>({...v,owned:(g.vehicles||[]).includes(v.id),until:(g.rentals?.[v.id]||0)>Date.now()?g.rentals[v.id]:0}))};}
 route(path,method,user,b){
  const id=user.id,db=this.db,p=this.game.players.get(id);ensureState(db,id);
  if(path==='/api/state'&&method==='GET')return this.snapshot(id);
  if(path==='/api/vehicles'&&method==='GET')return this.garage(id);
  if(path==='/api/dealer'&&method==='POST'){const d=DEALERS.find(q=>q.id===b.shop);if(!d)fail('Negozio sconosciuto');const g=state(db,id).progress;return {shop:d.id,balance:db.prepare('SELECT balance FROM player_state WHERE user_id=?').get(id).balance,active:p?.vehicle||null,vehicles:VEHICLES_3D.filter(v=>v.shop===d.id).map(v=>({...v,owned:(g.vehicles||[]).includes(v.id),until:0}))};}
  if(path==='/api/vehicle/buy'&&method==='POST'){const v=VEHICLE[b.id];if(!v?.buy)fail('Mezzo non acquistabile');if(v.shop){const d=DEALERS.find(q=>q.id===v.shop);if(!p||p.room!=='lungomare'||distance({x:d.x+d.w/2,y:d.y+d.h+1.2},p)>9)fail('Vai al negozio: '+d.name,403);}const s=state(db,id);const own=s.progress.vehicles||[];if(own.includes(v.id))fail('Lo possiedi già');this.pay(id,v.buy);const fresh=state(db,id).progress;fresh.vehicles=[...own,v.id];db.prepare('UPDATE player_state SET progress=? WHERE user_id=?').run(JSON.stringify(fresh),id);return this.garage(id);}
  if(path==='/api/vehicle/rent'&&method==='POST'){const v=VEHICLE[b.id];if(!v?.rent)fail('Mezzo non noleggiabile');this.pay(id,v.rent);const fresh=state(db,id).progress;fresh.rentals={...(fresh.rentals||{})};fresh.rentals[v.id]=Math.max(Date.now(),fresh.rentals[v.id]||0)+v.minutes*60000;fresh.activeVehicle=v.id;db.prepare('UPDATE player_state SET progress=? WHERE user_id=?').run(JSON.stringify(fresh),id);if(p)p.vehicle=v.id;return this.garage(id);}
  if(path==='/api/vehicle/use'&&method==='POST'){const remember=v=>{const g=state(db,id).progress;g.activeVehicle=v;db.prepare('UPDATE player_state SET progress=? WHERE user_id=?').run(JSON.stringify(g),id);};if(!b.id){if(p){const was=p.vehicle;p.vehicle=null;p.vel=0;p.music=null;
   // Scende dal lato del guidatore (a sinistra del muso), o dall'altro lato se lì c'è un ostacolo.
   if(was){const h=Number.isFinite(p.heading)?p.heading:p.direction||0;for(const side of [-1,1]){const x=p.x+Math.cos(h+side*Math.PI/2)*1.5,y=p.y+Math.sin(h+side*Math.PI/2)*1.5;if(canStand(p.room,x,y)){p.x=x;p.y=y;p.parkedAt={v:was,x:p.x-Math.cos(h+side*Math.PI/2)*1.5,y:p.y-Math.sin(h+side*Math.PI/2)*1.5,h,t:Date.now()};break;}}}}remember(null);return this.garage(id);}remember(b.id);if(!this.canUse(id,b.id))fail('Prima sblocca o noleggia questo mezzo',403);if(p?.room!=='lungomare'&&p?.room!=='mergellina')fail('Esci all’aperto per salire');if(p&&this.edition==='3d'&&['auto','furgone','cabrio'].includes(VEHICLE[b.id]?.base||b.id)&&!canStand(p.room,p.x,p.y,1.3)){let best=null;for(let r=.5;r<=7&&!best;r+=.5)for(let a=0;a<20;a++){const x=p.x+Math.cos(a/20*Math.PI*2)*r,y=p.y+Math.sin(a/20*Math.PI*2)*r;if(canStand(p.room,x,y,1.3)){best={x,y};break;}}if(best){p.x=best.x;p.y=best.y;}}if(p)p.vehicle=b.id;return this.garage(id);}

  if(path==='/api/settings'&&method==='PATCH'){const settings=cleanSettings(b);db.prepare('UPDATE player_state SET settings=? WHERE user_id=?').run(JSON.stringify(settings),id);return settings;}
  if(path==='/api/purchase'&&method==='POST')return this.purchase(id,b);
  if(path==='/api/villas'&&method==='GET')return Object.fromEntries(MAPS.lungomare.buildings.filter(v=>v.private).map(v=>[v.id,this.villaInfo(v.id,id)]));
  if(path==='/api/villa'&&method==='POST'){if(!['buy','rent'].includes(b.mode))fail('Scegli compra o affitta');return this.villaDeal(String(b.id||''),id,b.mode);}
  if(path==='/api/slot'&&method==='POST')return this.spin(id,Number(b.bet));
  if(path==='/api/fiches'&&method==='GET'){const s=state(db,id),day=new Date().toISOString().slice(0,10);return {fiches:s.progress.fichesDay===day?(s.progress.fiches??DAILY_FICHES):Math.max(s.progress.fiches??0,DAILY_FICHES)};}
  // Bancomat: cambia gemme in monete solo vicino a uno sportello (strada o interno della banca).
  if(path==='/api/atm/exchange'&&method==='POST'){const gems=Number(b.gems);if(!Number.isInteger(gems)||gems<1||gems>20)fail('Scegli da 1 a 20 gemme');if(!p||!MAPS[p.room]?.props.some(q=>q.kind==='atm'&&distance(q,p)<2))fail('Avvicinati a un bancomat',403);
   const changed=db.prepare("UPDATE player_state SET progress=json_set(progress,'$.gems',coalesce(json_extract(progress,'$.gems'),0)-?),balance=balance+? WHERE user_id=? AND coalesce(json_extract(progress,'$.gems'),0)>=?").run(gems,gems*ATM_RATE,id,gems).changes;if(!changed)fail('Gemme insufficienti');return this.snapshot(id);}
  // Luna park (solo 3D): si paga alla biglietteria e si viene seduti sulla giostra scelta; il giro dura qualche decina di secondi per tutti gli altri giocatori che guardano.
  if(path==='/api/giostra'&&method==='POST'){const R=FUNFAIR.rides[b.art];if(!R||!p||p.room!=='lungomare'||distance(FUNFAIR.booth,p)>6)fail('Vai alla biglietteria del luna park',403);if(p.seat||p.vehicle||p.ride)fail('Scendi prima dal mezzo');this.pay(id,R.price);const plan=ridePlan(b.art);p.input={x:0,y:0};p.seat='giostra';p.rideArt=b.art;p.rideA=plan.a0;p.ride={pts:plan.pts,uniform:true,a0:plan.a0,da:plan.da,t0:Date.now(),duration:R.seconds*1000,to:plan.to,msg:'🎡 Giro finito: sei sceso dalla giostra'};Object.assign(p,plan.pts[0]);return {...this.snapshot(id),seconds:R.seconds};}
  if(path==='/api/boat'&&method==='POST'){const B=p&&BOATS[p.room];if(!B||distance(B.dock,p)>4)fail('Vai al noleggio barche sul molo',403);if(p.seat||p.vehicle||p.ride)fail('Scendi prima dal mezzo');this.pay(id,BOAT_PRICE);const pts=[...B.route,...[...B.route].reverse().slice(1)].map(q=>({x:q[0],y:q[1]}));let len=0;for(let i=1;i<pts.length;i++)len+=distance(pts[i-1],pts[i]);p.input={x:0,y:0};p.seat='boat';const sp=B.speed||BOAT_SPEED;p.ride={pts,t0:Date.now(),duration:len/sp*1000,to:{x:B.dock.x,y:B.dock.y,name:'il molo'},boat:true};Object.assign(p,pts[0]);return {...this.snapshot(id),seconds:Math.round(len/sp)};}
  if(path==='/api/jukebox'&&method==='POST'){const jb=p&&JUKEBOX[p.room];if(!jb||distance(jb,p)>3)fail('Avvicinati al jukebox del locale',403);if(typeof b.id!=='string'||!/^[A-Za-z0-9_-]{11}$/.test(b.id))fail('Brano non valido');this.pay(id,JUKEBOX_PRICE);this.game.jukebox.set(p.room,{id:b.id,title:String(b.title||'').slice(0,80),at:Date.now(),until:Date.now()+JUKEBOX_MINUTES*60000,by:user.username});return {...this.snapshot(id),playing:true};}
  if(path==='/api/vending'&&method==='POST'){const d=DRINKS.find(q=>q.id===b.id);if(!d)fail('Bevanda sconosciuta');if(!p||!MAPS[p.room]?.props.some(q=>q.kind==='vending'&&distance(q,p)<2.4))fail('Avvicinati a un distributore',403);this.pay(id,d.price);const row=state(db,id);row.progress.drinks=(row.progress.drinks||0)+1;db.prepare('UPDATE player_state SET progress=? WHERE user_id=?').run(JSON.stringify(row.progress),id);return {...this.snapshot(id),drink:d.name};}
  if(path==='/api/reward'&&method==='POST'){if(p)savePlayer(db,p);const day=new Date().toISOString().slice(0,10);const result=db.prepare("UPDATE player_state SET progress=json_set(progress,'$.gems',coalesce(json_extract(progress,'$.gems'),0)+1),balance=balance+30,walked=walked-100,reward_day=? WHERE user_id=? AND walked>=100 AND reward_day<>?").run(day,id,day);if(!result.changes)fail('Cammina 100 metri per il premio giornaliero; un premio al giorno');return this.snapshot(id);}
  if(path==='/api/wear'&&method==='POST'){const avatar=JSON.parse(db.prepare('SELECT avatar FROM users WHERE id=?').get(id).avatar);avatar.wear={...(avatar.wear||{})};
   if(b.remove){if(!WEAR[b.remove])fail('Slot non valido');delete avatar.wear[b.remove];}else{const item=ITEMS.get(b.item);if(!item||item.type!=='wear'||!db.prepare('SELECT 1 FROM inventory WHERE user_id=? AND item=? AND quantity>0').get(id,item.id))fail('Capo non posseduto',403);avatar.wear[item.slot]={style:item.style,color:item.color,id:item.id};}
   db.prepare('UPDATE users SET avatar=? WHERE id=?').run(JSON.stringify(avatar),id);if(p)p.avatar=avatar;return avatar;}
  if(path==='/api/barber'&&method==='POST'){const hair=Number(b.hair),beard=Number(b.beard),color=Number(b.color);if(!p||p.room!=='barber')fail('Siediti dal Barbiere Totò',403);
   if(!(hair>=0&&hair<HAIR_STYLES.length&&beard>=0&&beard<BEARD_STYLES.length&&color>=0&&color<HAIR_COLORS.length)||![hair,beard,color].every(Number.isInteger))fail('Taglio non valido');
   if(!db.prepare('UPDATE player_state SET balance=balance-? WHERE user_id=? AND balance>=?').run(BARBER_PRICE,id,BARBER_PRICE).changes)fail('Servono '+BARBER_PRICE+' monete');
   const avatar={...JSON.parse(db.prepare('SELECT avatar FROM users WHERE id=?').get(id).avatar),hair:{style:hair,color:HAIR_COLORS[color][1]},beard};db.prepare('UPDATE users SET avatar=? WHERE id=?').run(JSON.stringify(avatar),id);if(p)p.avatar=avatar;return {avatar,balance:state(db,id).balance};}
  if(path==='/api/equip'&&method==='POST'){const item=CATALOG.find(i=>i.id===b.item&&i.type==='cosmetic');if(!item||!db.prepare('SELECT 1 FROM inventory WHERE user_id=? AND item=? AND quantity>0').get(id,item.id))fail('Oggetto non posseduto',403);const avatar={...JSON.parse(user.avatar),[item.slot]:item.value};if(item.color)avatar.color=item.color;db.prepare('UPDATE users SET avatar=? WHERE id=?').run(JSON.stringify(avatar),id);if(p)p.avatar=avatar;return avatar;}
  if(path==='/api/dm'&&method==='GET'){const peer=String(b.peer||'');if(this.game.blocked(id,peer))fail('Utente non disponibile',403);return db.prepare('SELECT d.*,u.username FROM direct_messages d JOIN users u ON u.id=d.sender WHERE (sender=? AND recipient=?) OR (sender=? AND recipient=?) ORDER BY d.id DESC LIMIT 50').all(id,peer,peer,id).reverse();}
  if(path==='/api/dm'&&method==='POST'){const target=String(b.id||''),text=String(b.text||'').trim();if(!text||text.length>500||target===id)fail('Messaggio non valido');if(!db.prepare('SELECT 1 FROM users WHERE id=?').get(target)||this.game.blocked(id,target))fail('Utente non disponibile',403);if(Date.now()-(this.lastDM.get(id)||0)<800)fail('Attendi prima del prossimo messaggio',429);this.lastDM.set(id,Date.now());const created=Date.now();db.prepare('INSERT INTO direct_messages(sender,recipient,text,created) VALUES(?,?,?,?)').run(id,target,text,created);this.notify(target,{type:'notification',message:'Messaggio privato da '+user.username,from:id});return {ok:true};}
  if(path==='/api/inbox'&&method==='GET')return db.prepare('SELECT d.id,d.sender,d.text,d.created,u.username FROM direct_messages d JOIN users u ON u.id=d.sender WHERE recipient=? ORDER BY d.id DESC LIMIT 30').all(id).filter(m=>!this.game.blocked(id,m.sender));
  if(path==='/api/home'&&method==='PATCH'){
   if(b.privacy!==undefined){if(!['PUBLIC','FRIENDS','PRIVATE'].includes(b.privacy))fail('Privacy non valida');db.prepare('UPDATE homes SET privacy=? WHERE owner=?').run(b.privacy,id);db.prepare('DELETE FROM home_invites WHERE owner=?').run(id);for(const guest of this.game.players.values())if(guest.room==='home:'+id&&!this.homeAllowed(id,guest.id))this.move(guest,'lungomare');}
   if(b.furniture!==undefined){if(!Array.isArray(b.furniture)||b.furniture.length>24)fail('Massimo 24 arredi');const counts={},positions=[];const furniture=b.furniture.map((f,i)=>{if(!f||typeof f!=='object')fail('Arredo non valido');const item=CATALOG.find(c=>c.id===f.item&&c.type==='furniture');if(!item||!Number.isFinite(f.x)||!Number.isFinite(f.y)||f.x<1||f.x>15||f.y<1||f.y>10.5)fail('Arredo fuori dai limiti');counts[item.id]=(counts[item.id]||0)+1;if(positions.some(q=>distance(q,f)<1.3))fail('Arredi troppo vicini');positions.push(f);return {id:'furniture'+i,item:item.id,x:f.x,y:f.y};});for(const [item,count] of Object.entries(counts)){const owned=db.prepare('SELECT quantity FROM inventory WHERE user_id=? AND item=?').get(id,item);if(!owned||owned.quantity<count)fail('Arredi non posseduti',403);}db.prepare('UPDATE homes SET furniture=? WHERE owner=?').run(JSON.stringify(furniture),id);this.homeMap(id);for(const guest of this.game.players.values())if(guest.room==='home:'+id){guest.seat=null;if(!canStand(guest.room,guest.x,guest.y))Object.assign(guest,MAPS[guest.room].spawn);}}
   return this.snapshot(id);
  }
  if(path==='/api/home/enter'&&method==='POST'){const owner=String(b.owner||id);if(!p)fail('Entra nel mondo');if(!this.homeAllowed(owner,id))fail('Appartamento privato',403);this.homeMap(owner);this.move(p,'home:'+owner);return {ok:true};}
  if(path==='/api/home/invite'&&method==='POST'){if(!this.friends(id,String(b.id))||this.game.blocked(id,String(b.id)))fail('Puoi invitare un amico non bloccato',403);db.prepare('INSERT INTO home_invites VALUES(?,?,?) ON CONFLICT(owner,guest) DO UPDATE SET expires=excluded.expires').run(id,b.id,Date.now()+3600000);this.notify(b.id,{type:'notification',message:user.username+' ti invita a casa per un’ora',home:id});return {ok:true};}
  if(path==='/api/events'&&method==='GET')return db.prepare("SELECT e.*,u.username FROM events e JOIN users u ON u.id=e.owner WHERE end_time>? AND status='scheduled' ORDER BY start_time LIMIT 30").all(Date.now()).filter(e=>!e.location.startsWith('home:')||this.homeAllowed(e.owner,id));
  if(path==='/api/events'&&method==='POST'){const start=Number(b.start_time),end=Number(b.end_time),location=b.location;const name=String(b.name||'').trim().slice(0,60);if(!name||!Number.isFinite(start)||!Number.isFinite(end)||start<Date.now()-60000||end<=start||end-start>4*3600000||start>Date.now()+30*86400000||!['club','lungomare','home:'+id].includes(location))fail('Dati evento non validi (massimo 4 ore)');if(db.prepare('SELECT count(*) n FROM events WHERE owner=? AND end_time>?').get(id,Date.now()).n>=3)fail('Massimo tre eventi futuri');db.prepare('INSERT INTO events(name,description,location,start_time,end_time,owner) VALUES(?,?,?,?,?,?)').run(name,String(b.description||'').slice(0,250),location,start,end,id);return {ok:true};}
  if(path==='/api/events/join'&&method==='POST'){const event=db.prepare('SELECT * FROM events WHERE id=? AND end_time>?').get(Number(b.id),Date.now());if(!event||event.location.startsWith('home:')&&!this.homeAllowed(event.owner,id))fail('Evento non disponibile',403);db.prepare('INSERT OR IGNORE INTO event_members VALUES(?,?)').run(event.id,id);return {ok:true,location:event.location};}
  return undefined;
 }
 villaInfo(id,viewer){const row=this.db.prepare('SELECT v.*,u.username FROM villas v JOIN users u ON u.id=v.owner WHERE v.id=? AND v.until>?').get(id,Date.now());
  return row?{status:row.owner===viewer?'mine':'taken',owner:row.username,mode:row.mode,until:row.until}:{status:'free',price:VILLA_PRICE,rent:VILLA_RENT,days:VILLA_RENT_DAYS};}
 villaAccess(user,id){return !!this.db.prepare('SELECT 1 FROM villas WHERE id=? AND owner=? AND until>?').get(id,user,Date.now());}
 villaDeal(id,user,mode){const p=this.game.players.get(user);const b=MAPS.lungomare.buildings.find(b=>b.id===id&&b.private);if(!b)fail('Villa inesistente');
  if(!p||p.room!=='lungomare'||distance(p,b.door)>3)fail('Vai davanti alla villa per comprarla o affittarla',403);
  const price=mode==='buy'?VILLA_PRICE:VILLA_RENT,until=mode==='buy'?8.64e15:Date.now()+VILLA_RENT_DAYS*86400000;ensureState(this.db,user);
  this.db.exec('BEGIN IMMEDIATE');try{
   const current=this.db.prepare('SELECT * FROM villas WHERE id=? AND until>?').get(id,Date.now());
   if(current&&current.owner!==user)fail('Villa già occupata');if(current&&current.mode==='buy')fail('La villa è già tua');
   if(this.db.prepare('SELECT count(*) n FROM villas WHERE owner=? AND until>? AND id<>?').get(user,Date.now(),id).n>=2)fail('Puoi avere al massimo due ville');
   if(!this.db.prepare('UPDATE player_state SET balance=balance-? WHERE user_id=? AND balance>=?').run(price,user,price).changes)fail(`Servono ${price} monete`);
   const newUntil=mode==='rent'&&current?current.until+VILLA_RENT_DAYS*86400000:until;
   this.db.prepare('INSERT INTO villas VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET owner=excluded.owner,mode=excluded.mode,until=excluded.until').run(id,user,mode,newUntil);this.db.exec('COMMIT');
  }catch(e){this.db.exec('ROLLBACK');throw e;}return {...this.villaInfo(id,user),balance:state(this.db,user).balance};}
 // Slot con fiches gratuite: 100 al giorno, esito deciso dal server con generatore crittografico.
 spin(user,bet){const p=this.game.players.get(user);if(!SLOT_BETS.includes(bet))fail('Puntata non valida');if(!p||p.room!=='casino'||!MAPS.casino.props.some(q=>q.kind==='slot'&&distance(q,p)<2))fail('Siediti davanti a una slot nella Sala Slot',403);
  ensureState(this.db,user);const s=state(this.db,user),day=new Date().toISOString().slice(0,10);let fiches=s.progress.fiches??DAILY_FICHES;if(s.progress.fichesDay!==day){fiches=Math.max(fiches,DAILY_FICHES);}
  if(fiches<bet)fail('Fiches finite: tornano domani (100 gratis al giorno)');
  const total=SLOT_SYMBOLS.reduce((a,x)=>a+x.w,0),roll=()=>{let r=randomInt(total);for(const x of SLOT_SYMBOLS){if(r<x.w)return x;r-=x.w;}};const reels=[roll(),roll(),roll()];
  const win=reels[0]===reels[1]&&reels[1]===reels[2]?bet*reels[0].x:(reels[0]===reels[1]||reels[1]===reels[2]||reels[0]===reels[2])?bet:0;fiches+=win-bet;
  this.db.prepare("UPDATE player_state SET progress=json_set(progress,'$.fiches',?,'$.fichesDay',?) WHERE user_id=?").run(fiches,day,user);return {reels:reels.map(x=>x.s),win,fiches};}
 notify(id,m){const p=this.game.players.get(id);if(p)this.game.send(p.ws,m);}
}
