import fs from 'node:fs';
const rep=(s,x,y)=>{if(!s.includes(x))throw new Error('manca: '+x.slice(0,80));return s.replace(x,()=>y);};
let f='client/world/ambient.js',s=fs.readFileSync(f,'utf8');
s=rep(s,"e.o.position.set(x,0,z);e.o.rotation.y=-q.direction+Math.PI/2*0;\n  // la macchina guarda dove va: stessa convenzione delle auto del traffico\n  e.o.rotation.y=Math.PI/2-q.direction;e.o.rotation.y=-(q.direction)+Math.PI/2;","e.o.position.set(x,0,z);e.o.rotation.y=w.hd(q.direction);");
s=rep(s,"e.o.rotation.y=-q.direction+Math.PI/2+.7;","e.o.rotation.y=w.hd(q.direction)+.7;");
fs.writeFileSync(f,s);
f='shared/traffic.js';s=fs.readFileSync(f,'utf8');
s=rep(s,"let limit=c.speed(c.s),pull=0;","let limit=c.speed(c.s)*(this.speedK||1),pull=0;");fs.writeFileSync(f,s);
f='client/world/citylife.js';s=fs.readFileSync(f,'utf8');
s=rep(s," sweeper:h=>between(h,6,12)?1:between(h,16,18)?.5:0,"," busker:()=>0,sweeper:h=>between(h,6,12)?1:between(h,16,18)?.5:0,");
s=rep(s,"sweeper:[2,3],crew:[4,4]};","sweeper:[2,3],crew:[4,4],busker:[4,4]};");
s=rep(s,"for(const a of this.agents){const want=a.u<DENS[a.kind](h);","for(const a of this.agents){if(a.manual)continue;const want=a.u<DENS[a.kind](h)*(a.kind==='crew'?1:this.weather??1);");
s=rep(s,"  if(a.state==='sit'||a.state==='wait'||a.state==='party'){","  if(a.state==='party'&&a.busk){a.act='Wave';return;}\n  if(a.state==='sit'||a.state==='wait'||a.state==='party'){");
// qualità dinamica: meno persone con il telefono in difficoltà, più quando va liscio
s=rep(s,"  this.group.visible=true;const h=hourNow(w),px=w.target.x,pz=w.target.z;","  this.group.visible=true;const h=hourNow(w),px=w.target.x,pz=w.target.z;\n  this.ema=(this.ema??dt)*.96+Math.min(dt,.2)*.04;this.qt=(this.qt||0)+dt;if(this.qt>2.5){this.qt=0;if(this.ema>.046&&this.max>4){this.max--;this.radius=Math.max(30,this.radius-3);}else if(this.ema<.03&&this.max<this.cap){this.max++;this.radius=Math.min(this.rcap,this.radius+3);}}");
s=rep(s,"this.max=w.mobile?8:14;this.radius=w.mobile?44:56;","this.max=this.cap=w.mobile?8:14;this.radius=this.rcap=w.mobile?44:56;");
fs.writeFileSync(f,s);
f='client/world/world3d.js';s=fs.readFileSync(f,'utf8');
s=rep(s,"import {CityLife} from './citylife.js';","import {CityLife} from './citylife.js';import {Ambient} from './ambient.js';");
s=rep(s,"try{(this.life??=new CityLife(this)).update(dt,list);}catch(e){if(!this.lifeErr2){this.lifeErr2=1;console.warn('citylife',e);}}","try{(this.life??=new CityLife(this)).update(dt,list);}catch(e){if(!this.lifeErr2){this.lifeErr2=1;console.warn('citylife',e);}}try{(this.amb??=new Ambient(this)).update(dt,list);}catch(e){if(!this.ambErr){this.ambErr=1;console.warn('ambiente',e);}}");
s=rep(s,"  if(this.room!=='lungomare')this.life?.hide();","  if(this.room!=='lungomare'){this.life?.hide();this.amb?.hide();}");
s=rep(s,"...(this.life?.crossers()||[])]);","...(this.life?.crossers()||[]),...(this.amb?.obstacles()||[])]);");
s=rep(s," // Camion dei rifiuti ESI"," hd(d){return heading(d);}\n // Camion dei rifiuti ESI");
s=rep(s,"this.share(o);id.g.add(o);};\n   const k=p.kind,","this.share(o);id.g.add(o);if(p.kind==='palm'||p.kind==='tree')(this.sway??=[]).push({o,ph:p.x*.7+p.y*1.3});};\n   const k=p.kind,");
fs.writeFileSync(f,s);
f='client/sw.js';s=fs.readFileSync(f,'utf8');s=rep(s,"'/world/citylife.js',","'/world/citylife.js','/world/ambient.js',").replace(/humana-life-\d+/,m=>'humana-life-'+(Number(m.split('-').pop())+1));fs.writeFileSync(f,s);
console.log('ok');
