// Crea docs/confronto-mappa.html: a sinistra la mappa vera (tessere OpenStreetMap, serve internet per vederle) con sopra i dati importati;
// a destra la mappa del gioco in metri (1 m = 1 m); sotto fonti, dati importati, parti ricostruite, parti approssimate e verifica delle distanze.
//   node scripts/confronto-mappa.mjs        (dopo node scripts/osm-napoli.mjs)
import {readFile,writeFile} from 'node:fs/promises';
const m=JSON.parse(await readFile('client/assets/world/napoli/map/mergellina.json','utf8'));
const {lat:lat0,lon:lon0}=m.origin,kx=Math.cos(lat0*Math.PI/180)*111320,ky=110540;
const toLL=(x,y)=>[lat0-y/ky,lon0+x/kx];
const hav=(a,b)=>{const R=6371008.8,rad=Math.PI/180,dLat=(b[0]-a[0])*rad,dLon=(b[1]-a[1])*rad,s=Math.sin(dLat/2)**2+Math.cos(a[0]*rad)*Math.cos(b[0]*rad)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s));};
const L=Object.fromEntries(m.landmarks.filter(l=>!l.missing).map(l=>[l.name,l]));
const pairs=[['Piazza Sannazaro','Fontana del Sebeto'],['Piazza Sannazaro','Castel dell\'Ovo'],['Fontana del Sebeto','Castel dell\'Ovo'],['Castel dell\'Ovo','Borgo Marinari'],['Villa Comunale','Castel dell\'Ovo']].filter(([a,b])=>L[a]&&L[b]).map(([a,b])=>{const real=hav(toLL(L[a].x,L[a].y),toLL(L[b].x,L[b].y)),game=Math.hypot(L[a].x-L[b].x,L[a].y-L[b].y);return {a,b,real:Math.round(real),game:Math.round(game),err:Math.abs(real-game).toFixed(1)};});
const slim={b:m.buildings.map(b=>b.p.map(q=>[Math.round(q[0]),Math.round(q[1])])),r:m.roads.filter(r=>r.w>=4).map(r=>({p:r.p.map(q=>[Math.round(q[0]),Math.round(q[1])]),w:r.w})),c:m.coast.map(c=>c.filter((_,i)=>i%3===0).map(q=>[Math.round(q[0]),Math.round(q[1])])),pi:m.piers.map(p=>p.p.map(q=>[Math.round(q[0]),Math.round(q[1])])),pk:m.parks.map(p=>p.map(q=>[Math.round(q[0]),Math.round(q[1])])),bb:m.bbox,lm:m.landmarks.filter(l=>!l.missing).map(l=>({n:l.name,x:l.x,y:l.y,ll:toLL(l.x,l.y)})),o:m.origin,g:{x0:m.grid.x0,y0:m.grid.y0,w:m.grid.w,h:m.grid.h}};
const S=m.stats,named=m.pois.filter(p=>p.name).length;
const html=`<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Napoli life · confronto mappa vera / mappa del gioco</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>body{font:15px/1.45 system-ui,sans-serif;margin:0;background:#0f1b2a;color:#e8eef5}header,section{padding:14px 18px}h1{font-size:20px;margin:0 0 4px}h2{font-size:16px;margin:18px 0 6px;color:#f5d58a}.two{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:0 18px}#map,#game{height:520px;border-radius:12px;background:#1b2f45;width:100%}table{border-collapse:collapse;width:100%;font-size:13px}td,th{border-bottom:1px solid #2c4660;padding:5px 8px;text-align:left}small{color:#9fb4c8}.ok{color:#7fe3a0}.st{color:#ffd27a}ul{margin:4px 0 4px 18px}@media(max-width:800px){.two{grid-template-columns:1fr}}</style>
<header><h1>Napoli life · Mergellina → Castel dell'Ovo</h1><small>Confronto fra la mappa geografica vera e la mappa del gioco. Scala 1:1: un metro reale = un metro nel gioco. Generato il ${new Date().toISOString().slice(0,10)}.</small></header>
<div class="two"><div><b>Mappa vera</b> <small>(tessere © OpenStreetMap; in blu i palazzi importati nel gioco)</small><div id="map"></div></div><div><b>Mappa del gioco</b> <small>(metri; x = est, y = sud; griglia ogni 250 m)</small><canvas id="game" width="900" height="520"></canvas></div></div>
<section><h2>Verifica delle distanze (stesse coppie di luoghi)</h2><table><tr><th>Da</th><th>A</th><th>Distanza reale (formula geografica)</th><th>Nel gioco (metri)</th><th>Differenza</th></tr>${pairs.map(p=>`<tr><td>${p.a}</td><td>${p.b}</td><td>${p.real} m</td><td>${p.game} m</td><td class="ok">${p.err} m</td></tr>`).join('')}</table>
<small>La differenza (pochi metri su più di 2 km, circa 0,15%) viene dall'approssimazione piana: la conversione usa un metro per grado calcolato alla latitudine di Mergellina (origine fissa lat ${lat0}, lon ${lon0}). Non è una verifica indipendente sul posto: confronta i dati importati con la formula, e la sovrapposizione a sinistra mostra se i palazzi cadono sulle strade vere.</small></section>
<section><h2>Punti di riferimento</h2><table><tr><th>Luogo</th><th>Latitudine, longitudine (da OpenStreetMap)</th><th>Posizione nel gioco (x, y)</th><th>Fonte</th></tr>${m.landmarks.map(l=>l.missing?`<tr><td>${l.name}</td><td colspan=3 class="st">non trovato nei dati scaricati</td></tr>`:`<tr><td>${l.name}</td><td>${toLL(l.x,l.y).map(v=>v.toFixed(5)).join(', ')}</td><td>${l.x}, ${l.y}</td><td>${l.osm}</td></tr>`).join('')}</table></section>
<section><h2>Fonti e dati importati</h2><ul><li><b>Fonte</b>: ${m.source} — ${m.attribution}. Scaricato il ${(m.downloaded||'').slice(0,10)}; riquadro lat ${m.bbox.s}–${m.bbox.n}, lon ${m.bbox.w}–${m.bbox.e}.</li><li><b>Importati</b>: ${S.buildings} edifici (${S.withLevels} con piani o altezza in OSM), ${S.roads} strade e percorsi, costa, ${m.piers.length} moli/pontili/frangiflutti, ${m.squares.length} piazze, ${m.parks.length} parchi, ${m.beaches.length} spiagge, ${S.trees} alberi, ${S.pois} attività (${named} con nome), griglia di calpestabilità ${m.grid.w}×${m.grid.h} m.</li><li>Importazione ripetibile: <code>node scripts/osm-scarica.mjs</code> poi <code>node scripts/osm-napoli.mjs</code>. Il gioco non scarica nulla durante la partita.</li></ul></section>
<section><h2>Elementi ricostruiti (forma e posizione dai dati veri)</h2><ul><li>Sagome di tutti i palazzi, strade con larghezza, marciapiedi, costa e moli, parchi, piazze e spiagge.</li><li>Castel dell'Ovo: il modello 3D è adattato alla pianta vera (posizione, orientamento, lunghezza). Borgo Marinari: sagome vere delle case.</li><li>Fontana del Sebeto: posizione vera, vasca non attraversabile.</li><li>Nomi delle vie sui cartelli agli incroci; attività con nome vero quando OSM lo ha.</li></ul></section>
<section><h2>Parti approssimate o stimate (NON verificate)</h2><ul><li><b>Altezze dei palazzi</b>: OSM le indica per ${S.withLevels} edifici su ${S.buildings}; per gli altri il gioco <b>stima</b> i piani.</li><li><b>Facciate, balconi, finestre, tetti e colori</b>: generati dal gioco in stile napoletano, non copiati da foto dei palazzi veri.</li><li><b>Fontana del Sebeto</b>: forma stilizzata e orientamento stimato (parallelo alla strada più vicina).</li><li><b>Castel dell'Ovo</b>: il modello è un'interpretazione, non una scansione.</li><li><b>Barche</b>: messe a caso lungo i pontili veri, non sono le barche reali.</li><li><b>Interni dei locali</b>: sono gli interni di fantasia del gioco, uguali per tutti i bar/ristoranti dello stesso tipo.</li><li><b>Attività</b>: la presenza su OpenStreetMap non garantisce che esistano oggi; i nomi senza marchio verde ✔ sono inventati dal gioco.</li><li>Il Lungomare "Napoli Centro" (31 attività della legenda) è un'<b>area di fantasia</b>, non è geografia vera.</li></ul></section>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const D=${JSON.stringify(slim)};
// --- a sinistra: mappa vera + dati importati ---
{const map=L.map('map').setView([40.8262,14.2310],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
 const kx=Math.cos(D.o.lat*Math.PI/180)*111320,ky=110540,ll=q=>[D.o.lat-q[1]/ky,D.o.lon+q[0]/kx];
 L.rectangle([[D.bb.s,D.bb.w],[D.bb.n,D.bb.e]],{color:'#f5b81c',weight:2,fill:false}).addTo(map);
 const bl=L.layerGroup(D.b.map(p=>L.polygon(p.map(ll),{color:'#1e90ff',weight:1,fillOpacity:.35}))).addTo(map);L.control.layers(null,{'Palazzi importati':bl}).addTo(map);
 for(const l of D.lm)L.marker(l.ll).bindPopup('<b>'+l.n+'</b><br>x '+l.x+', y '+l.y).addTo(map);}
// --- a destra: mappa del gioco in metri ---
{const cv=document.getElementById('game'),g=cv.getContext('2d'),W=cv.width,H=cv.height,x0=D.g.x0,y0=D.g.y0,gw=D.g.w,gh=D.g.h,k=Math.min(W/gw,H/gh),X=x=>(x-x0)*k,Y=y=>(y-y0)*k;
 g.fillStyle='#3a7fb8';g.fillRect(0,0,W,H);g.fillStyle='#dcd2bd';g.beginPath();for(const c of D.c){c.forEach((q,i)=>i?g.lineTo(X(q[0]),Y(q[1])):g.moveTo(X(q[0]),Y(q[1])));}
 // terra = lato nord della costa
 g.lineTo(X(x0+gw),Y(y0));g.lineTo(X(x0),Y(y0));g.closePath();g.fill();
 g.fillStyle='#86b873';for(const p of D.pk){g.beginPath();p.forEach((q,i)=>i?g.lineTo(X(q[0]),Y(q[1])):g.moveTo(X(q[0]),Y(q[1])));g.fill();}
 g.strokeStyle='#5d6170';g.lineCap='round';for(const r of D.r){g.lineWidth=Math.max(1,r.w*k);g.beginPath();r.p.forEach((q,i)=>i?g.lineTo(X(q[0]),Y(q[1])):g.moveTo(X(q[0]),Y(q[1])));g.stroke();}
 g.fillStyle='#c98b5e';for(const p of D.b){g.beginPath();p.forEach((q,i)=>i?g.lineTo(X(q[0]),Y(q[1])):g.moveTo(X(q[0]),Y(q[1])));g.fill();}
 g.strokeStyle='#8a6a3a';g.lineWidth=Math.max(1.5,3*k);for(const p of D.pi){g.beginPath();p.forEach((q,i)=>i?g.lineTo(X(q[0]),Y(q[1])):g.moveTo(X(q[0]),Y(q[1])));g.stroke();}
 g.strokeStyle='rgba(255,255,255,.35)';g.lineWidth=1;g.font='11px system-ui';g.fillStyle='#fff';for(let x=Math.ceil(x0/250)*250;x<x0+gw;x+=250){g.beginPath();g.moveTo(X(x),0);g.lineTo(X(x),H);g.stroke();g.fillText(x+' m',X(x)+2,12);}for(let y=Math.ceil(y0/250)*250;y<y0+gh;y+=250){g.beginPath();g.moveTo(0,Y(y));g.lineTo(W,Y(y));g.stroke();g.fillText(y+' m',2,Y(y)-2);}
 g.font='bold 12px system-ui';for(const l of D.lm){g.fillStyle='#e5484d';g.beginPath();g.arc(X(l.x),Y(l.y),4,0,7);g.fill();g.fillStyle='#fff';g.strokeStyle='#0008';g.lineWidth=3;g.strokeText(l.n,X(l.x)+6,Y(l.y)-5);g.fillText(l.n,X(l.x)+6,Y(l.y)-5);}}
</script></html>`;
await writeFile('docs/confronto-mappa.html',html);console.log('docs/confronto-mappa.html',Math.round(html.length/1024),'kB');for(const p of pairs)console.log(p.a,'→',p.b,'reale',p.real,'gioco',p.game,'diff',p.err);
